import IsoGraph.Canon.Subtree
import IsoGraph.Canon.Group

/-!
# The stabiliser chain: a complete set of automorphism generators

`Canon/Group.lean` collects the automorphisms the canonical labelling search happened to harvest.
Those are genuine automorphisms, but there is no reason for them to generate the whole group —
the search prunes, and `St.addAuto` stops recording after `maxGens` of them.  This file computes
a generating set that provably *is* complete, by the textbook orbit–stabiliser recursion, using
the decidable orbit test of `Canon/Subtree.lean`.

## What is here

* `chainGens n f fuel path` — the recursion.  At the node reached by `path`, take the target cell
  `c` that the refinement is about to split, fix its first vertex `v₀`, recurse below
  `path.push v₀` to generate the stabiliser of one more point, and then add one coset
  representative for every vertex `v` of `c` that the orbit test finds in the orbit of `v₀`.
* `chainArrays n adj` — the top-level call, at the root, with enough fuel for `n + 1` levels
  (`numCells_le` bounds the depth).
* `chain_complete` — the mathematical content: every automorphism fixing `path` pointwise is a
  product of the generators below `path`.  The proof is orbit–stabiliser: `σ` moves `v₀` to some
  `v` in the same cell, the orbit test therefore succeeds and contributes a `τ` doing the same, and
  `τ⁻¹ * σ` fixes one more point, so induction applies.
* `autGroup_eq_closure` — **completeness**: `autGroup n adj` is *equal to* the group generated by
  `chainArrays n adj`, not merely a supergroup of it.  `closure_fullGens` says the same thing with
  the generators packaged as elements of `autGroup n adj` (`fullGens`).
-/

set_option autoImplicit false
namespace IsoGraph
namespace Canon

open Std

/-! ## The stabiliser chain -/

/-- The vertices of the cell of `p` that starts at position `c`. -/
def cellOf (n : Nat) (p : Part) (c : Nat) : List Nat :=
  (List.range n).filter fun v => p.cst[p.pos[v]!]! == c

theorem mem_cellOf {n : Nat} {p : Part} {c v : Nat} :
    v ∈ cellOf n p c ↔ v < n ∧ p.cst[p.pos[v]!]! = c := by
  simp [cellOf, List.mem_filter, List.mem_range]

/-- One level of the chain: a coset representative for every vertex of the target cell that is in
the orbit of the base point `p.lab[c]!`, on top of the generators of the level below. -/
def chainStep (n : Nat) (f : Nat → Nat → Bool) (path : Array Nat) (p : Part) (c : Nat)
    (below : Array (Array Nat)) : Array (Array Nat) :=
  (cellOf n p c).foldl (fun acc v =>
    if sameOrbit n f (path.push p.lab[c]!) (path.push v) then
      acc.push (orbitMap n f (path.push p.lab[c]!) (path.push v))
    else acc) below

/-- **The stabiliser chain of the node at `path`**: generators for the group of automorphisms
fixing every vertex of `path`. -/
def chainGens (n : Nat) (f : Nat → Nat → Bool) : Nat → Array Nat → Array (Array Nat)
  | 0, _ => #[]
  | fuel + 1, path =>
    match ((nodePath n f path.toList).2).targetCell n with
    | none => #[]
    | some c =>
      chainStep n f path ((nodePath n f path.toList).2) c
        (chainGens n f fuel (path.push (((nodePath n f path.toList).2).lab[c]!)))

theorem chainGens_succ_none {n : Nat} {f : Nat → Nat → Bool} {fuel : Nat} {path : Array Nat}
    {p : Part} (hp : (nodePath n f path.toList).2 = p) (hc : p.targetCell n = none) :
    chainGens n f (fuel + 1) path = #[] := by
  rw [chainGens, hp, hc]

theorem chainGens_succ_some {n : Nat} {f : Nat → Nat → Bool} {fuel : Nat} {path : Array Nat}
    {p : Part} {c : Nat} (hp : (nodePath n f path.toList).2 = p)
    (hc : p.targetCell n = some c) :
    chainGens n f (fuel + 1) path
      = chainStep n f path p c (chainGens n f fuel (path.push p.lab[c]!)) := by
  rw [chainGens, hp, hc]

/-! ### Membership in a conditional fold -/

theorem mem_foldl_push_of_mem_init {α β : Type} (F : α → β) (T : α → Bool) :
    ∀ (l : List α) (init : Array β) (x : β), x ∈ init →
      x ∈ l.foldl (fun acc a => if T a then acc.push (F a) else acc) init
  | [], _, _, hx => hx
  | a :: l, init, x, hx => by
    rw [List.foldl_cons]
    refine mem_foldl_push_of_mem_init F T l _ x ?_
    by_cases h : T a = true
    · rw [if_pos h]; simp [Array.mem_push, hx]
    · rw [if_neg h]; exact hx

theorem mem_foldl_push {α β : Type} (F : α → β) (T : α → Bool) :
    ∀ (l : List α) (init : Array β) (a : α), a ∈ l → T a = true →
      F a ∈ l.foldl (fun acc x => if T x then acc.push (F x) else acc) init
  | b :: l, init, a, ha, hT => by
    rw [List.foldl_cons]
    rcases List.mem_cons.1 ha with rfl | ha'
    · refine mem_foldl_push_of_mem_init F T l _ _ ?_
      rw [if_pos hT]; simp [Array.mem_push]
    · exact mem_foldl_push F T l _ a ha' hT

theorem mem_chainStep_of_mem_below {n : Nat} {f : Nat → Nat → Bool} {path : Array Nat} {p : Part}
    {c : Nat} {below : Array (Array Nat)} {x : Array Nat} (hx : x ∈ below) :
    x ∈ chainStep n f path p c below :=
  mem_foldl_push_of_mem_init _ _ _ _ _ hx

theorem mem_chainStep {n : Nat} {f : Nat → Nat → Bool} {path : Array Nat} {p : Part} {c v : Nat}
    {below : Array (Array Nat)} (hv : v ∈ cellOf n p c)
    (h : sameOrbit n f (path.push p.lab[c]!) (path.push v) = true) :
    orbitMap n f (path.push p.lab[c]!) (path.push v) ∈ chainStep n f path p c below :=
  mem_foldl_push _ _ _ _ v hv h

/-! ### Between permutations of `Fin n` and arrays -/

/-- A permutation of `Fin n` in array form. -/
def arrOfPerm (n : Nat) (σ : Equiv.Perm (Fin n)) : Array Nat :=
  Array.ofFn fun i : Fin n => (σ i).1

theorem arrOfPerm_get {n : Nat} (σ : Equiv.Perm (Fin n)) {i : Nat} (hi : i < n) :
    (arrOfPerm n σ)[i]! = (σ ⟨i, hi⟩).1 := by
  rw [arrOfPerm, getElem!_pos _ i (by simpa using hi)]
  simp

theorem arrOfPerm_isAuto {n : Nat} {adj : Fin n → Fin n → Bool} {σ : Equiv.Perm (Fin n)}
    (hσ : σ ∈ autGroup n adj) : IsAutoArr n (oracleOfFin n adj) (arrOfPerm n σ) := by
  refine ⟨⟨by simp [arrOfPerm], fun i hi => ?_, fun i hi j hj hij => ?_⟩, fun u hu v hv => ?_⟩
  · rw [arrOfPerm_get σ hi]; exact (σ ⟨i, hi⟩).2
  · rw [arrOfPerm_get σ hi, arrOfPerm_get σ hj] at hij
    have := σ.injective (Fin.ext hij)
    exact congrArg Fin.val this
  · rw [arrOfPerm_get σ hu, arrOfPerm_get σ hv,
      oracleOfFin_apply adj (σ ⟨u, hu⟩).2 (σ ⟨v, hv⟩).2, oracleOfFin_apply adj hu hv,
      Fin.eta, Fin.eta]
    exact hσ ⟨u, hu⟩ ⟨v, hv⟩

/-! ### The chain generates the pointwise stabiliser -/

theorem mem_toList_iff {a : Array Nat} {x : Nat} : x ∈ a.toList ↔ ∃ j, j < a.size ∧ a[j]! = x := by
  constructor
  · intro h
    obtain ⟨j, hj, hji⟩ := List.getElem_of_mem h
    exact ⟨j, by simpa using hj, by rw [getElem!_pos a j (by simpa using hj)]; simpa using hji⟩
  · rintro ⟨j, hj, rfl⟩
    rw [getElem!_pos a j hj]
    exact List.getElem_mem _

/-- The permutations of `Fin n` named by an array of arrays. -/
def permsOf (n : Nat) (gs : Array (Array Nat)) : Set (Equiv.Perm (Fin n)) :=
  {σ | ∃ g ∈ gs, ∀ i : Fin n, (σ i).1 = g[i.1]!}

theorem permsOf_mono {n : Nat} {gs hs : Array (Array Nat)} (h : ∀ g ∈ gs, g ∈ hs) :
    permsOf n gs ⊆ permsOf n hs := by rintro σ ⟨g, hg, hσ⟩; exact ⟨g, h g hg, hσ⟩

/-- **Completeness of the stabiliser chain.**  Every automorphism fixing every vertex of `path`
lies in the group generated by the chain computed at `path`. -/
theorem chain_complete (n : Nat) (adj : Fin n → Fin n → Bool) :
    ∀ (fuel : Nat) (path : Array Nat) (ip : Array UInt64) (p : Part),
      Node n (oracleOfFin n adj) path ip p → n + 1 ≤ numCells n p + fuel →
      ∀ σ : Equiv.Perm (Fin n), σ ∈ autGroup n adj →
        (∀ i : Fin n, i.1 ∈ path.toList → σ i = i) →
        σ ∈ Subgroup.closure (permsOf n (chainGens n (oracleOfFin n adj) fuel path)) := by
  intro fuel
  induction fuel with
  | zero =>
    intro path ip p _ hfuel σ _ _
    exact absurd (numCells_le (n := n) p) (by omega)
  | succ fuel ih =>
    intro path ip p hnode hfuel σ hσ hfix
    have hnp : (nodePath n (oracleOfFin n adj) path.toList).2 = p :=
      congrArg Prod.snd hnode.nodePath_eq
    have hwf := hnode.wf
    have hg : IsAutoArr n (oracleOfFin n adj) (arrOfPerm n σ) := arrOfPerm_isAuto hσ
    have hfixarr : ∀ i, i < path.size → (arrOfPerm n σ)[path[i]!]! = path[i]! := by
      intro i hi
      have hlt := hnode.path_lt i hi
      rw [arrOfPerm_get σ hlt, hfix ⟨path[i]!, hlt⟩ (mem_toList_iff.2 ⟨i, hi, rfl⟩)]
    cases htc : p.targetCell n with
    | none =>
      have hone : σ = 1 := by
        have hdisc := discrete_of_targetCell_none hwf htc
        have he := hnode.auto_partEquiv hg hfixarr
        refine Equiv.ext fun i => Fin.ext ?_
        have h1 := he.cell i.1 i.2
        have hgi : (arrOfPerm n σ)[i.1]! < n := hg.perm.lt i.1 i.2
        rw [hdisc _ (hwf.posLt _ hgi), hdisc _ (hwf.posLt _ i.2)] at h1
        have h2 := congrArg (fun k => p.lab[k]!) h1
        rw [hwf.labPos _ hgi, hwf.labPos _ i.2, arrOfPerm_get σ i.2] at h2
        simpa using h2
      rw [hone]; exact one_mem _
    | some c =>
      have hc : c < n := targetCell_lt n p c htc
      have hv0 : p.lab[c]! < n := hwf.labLt c hc
      have hcell0 : p.cst[p.pos[p.lab[c]!]!]! = c := by
        rw [hwf.posLab c hc]; exact targetCell_cst hwf htc
      have hnode0 := hnode.step htc hv0 hcell0
      have hpe : PartEquiv n (fun x => (arrOfPerm n σ)[x]!) p p := hnode.auto_partEquiv hg hfixarr
      have hv : (arrOfPerm n σ)[p.lab[c]!]! < n := hg.perm.lt _ hv0
      have hcellv : p.cst[p.pos[(arrOfPerm n σ)[p.lab[c]!]!]!]! = c := by
        rw [hpe.cell _ hv0]; exact hcell0
      have hnodev := hnode.step htc hv hcellv
      have hsizeP : (path.push p.lab[c]!).size = (path.push (arrOfPerm n σ)[p.lab[c]!]!).size := by
        simp
      have hmapinv : ∀ i, i < (path.push (arrOfPerm n σ)[p.lab[c]!]!).size →
          (path.push p.lab[c]!)[i]!
            = (invAuto n (arrOfPerm n σ))[(path.push (arrOfPerm n σ)[p.lab[c]!]!)[i]!]! := by
        intro i hi
        rw [Array.size_push] at hi
        rcases Nat.lt_or_ge i path.size with h1 | h1
        · have h2 := invAuto_get hg.perm (hnode.path_lt i h1)
          rw [hfixarr i h1] at h2
          rw [push_getElem!_lt _ _ h1, push_getElem!_lt _ _ h1, h2]
        · have hieq : i = path.size := by omega
          subst hieq
          rw [push_getElem!_eq, push_getElem!_eq]
          exact (invAuto_get hg.perm hv0).symm
      have hso := sameOrbit_of_auto hnode0 hnodev (invAuto_isAuto hg) hsizeP hmapinv
      obtain ⟨hdauto, -, hdmaps⟩ := sameOrbit_spec hso
      have hdmem : orbitMap n (oracleOfFin n adj) (path.push p.lab[c]!)
          (path.push (arrOfPerm n σ)[p.lab[c]!]!)
            ∈ chainGens n (oracleOfFin n adj) (fuel + 1) path := by
        rw [chainGens_succ_some hnp htc]
        exact mem_chainStep (mem_cellOf.2 ⟨hv, hcellv⟩) hso
      have hτval : ∀ i : Fin n,
          (permOfArrays n _ (invArray n (orbitMap n (oracleOfFin n adj) (path.push p.lab[c]!)
            (path.push (arrOfPerm n σ)[p.lab[c]!]!))) i).1
              = (orbitMap n (oracleOfFin n adj) (path.push p.lab[c]!)
                  (path.push (arrOfPerm n σ)[p.lab[c]!]!))[i.1]! := fun i =>
        permOfArrays_val hdauto.perm.isPerm
          (fun x hx => invArray_apply hdauto.perm.size hdauto.perm.isPerm x hx) i
      set τ := permOfArrays n (orbitMap n (oracleOfFin n adj) (path.push p.lab[c]!)
        (path.push (arrOfPerm n σ)[p.lab[c]!]!))
        (invArray n (orbitMap n (oracleOfFin n adj) (path.push p.lab[c]!)
          (path.push (arrOfPerm n σ)[p.lab[c]!]!))) with hτ_def
      have hτaut : τ ∈ autGroup n adj := permOfArrays_mem_autGroup hdauto
      have hτmem : τ ∈ Subgroup.closure
          (permsOf n (chainGens n (oracleOfFin n adj) (fuel + 1) path)) :=
        Subgroup.subset_closure ⟨_, hdmem, hτval⟩
      have hagree : ∀ i : Fin n, i.1 ∈ (path.push p.lab[c]!).toList → σ i = τ i := by
        intro i hi
        refine Fin.ext ?_
        rw [hτval i]
        obtain ⟨j, hj, hji⟩ := mem_toList_iff.1 hi
        rw [Array.size_push] at hj
        rcases Nat.lt_or_ge j path.size with h1 | h1
        · rw [push_getElem!_lt _ _ h1] at hji
          rw [hfix i (mem_toList_iff.2 ⟨j, h1, hji⟩), ← hji]
          have h2 := hdmaps j (by rw [Array.size_push]; omega)
          rw [push_getElem!_lt _ _ h1, push_getElem!_lt _ _ h1] at h2
          exact h2.symm
        · have hjeq : j = path.size := by omega
          subst hjeq
          rw [push_getElem!_eq] at hji
          have h2 := hdmaps path.size (by rw [Array.size_push]; omega)
          rw [push_getElem!_eq, push_getElem!_eq] at h2
          rw [← hji, h2, arrOfPerm_get σ hv0]
          exact congrArg (fun x => ((σ x : Fin n) : Nat)) (Fin.ext hji.symm)
      have hfix' : ∀ i : Fin n, i.1 ∈ (path.push p.lab[c]!).toList → (τ⁻¹ * σ) i = i := by
        intro i hi
        show τ⁻¹ (σ i) = i
        rw [hagree i hi]
        exact τ.symm_apply_apply i
      have hbelow := ih (path.push p.lab[c]!) _ _ hnode0
        (by have := numCells_child (f := oracleOfFin n adj) hwf htc hv0 hcell0; omega)
        (τ⁻¹ * σ) (mul_mem (inv_mem hτaut) hσ) hfix'
      have hmono : Subgroup.closure
            (permsOf n (chainGens n (oracleOfFin n adj) fuel (path.push p.lab[c]!)))
          ≤ Subgroup.closure (permsOf n (chainGens n (oracleOfFin n adj) (fuel + 1) path)) := by
        refine Subgroup.closure_mono (permsOf_mono ?_)
        intro x hx
        rw [chainGens_succ_some hnp htc]
        exact mem_chainStep_of_mem_below hx
      have hfact : σ = τ * (τ⁻¹ * σ) := (mul_inv_cancel_left τ σ).symm
      rw [hfact]
      exact mul_mem hτmem (hmono hbelow)

/-! ### Soundness: everything the chain computes is an automorphism -/

theorem mem_foldl_push_cases {α β : Type} (F : α → β) (T : α → Bool) :
    ∀ (l : List α) (init : Array β) (x : β),
      x ∈ l.foldl (fun acc a => if T a then acc.push (F a) else acc) init →
        x ∈ init ∨ ∃ a ∈ l, T a = true ∧ x = F a
  | [], _, _, hx => Or.inl hx
  | a :: l, init, x, hx => by
    rw [List.foldl_cons] at hx
    rcases mem_foldl_push_cases F T l _ x hx with h | ⟨b, hb, hTb, hxb⟩
    · by_cases hT : T a = true
      · rw [if_pos hT] at h
        rcases Array.mem_push.1 h with h' | h'
        · exact Or.inl h'
        · exact Or.inr ⟨a, List.mem_cons_self .., hT, h'⟩
      · rw [if_neg hT] at h; exact Or.inl h
    · exact Or.inr ⟨b, List.mem_cons_of_mem _ hb, hTb, hxb⟩

theorem chainGens_isAuto (n : Nat) (f : Nat → Nat → Bool) :
    ∀ (fuel : Nat) (path : Array Nat) (g : Array Nat), g ∈ chainGens n f fuel path →
      IsAutoArr n f g := by
  intro fuel
  induction fuel with
  | zero => intro path g hg; rw [chainGens] at hg; simp at hg
  | succ fuel ih =>
    intro path g hg
    cases htc : ((nodePath n f path.toList).2).targetCell n with
    | none => rw [chainGens_succ_none rfl htc] at hg; simp at hg
    | some c =>
      rw [chainGens_succ_some rfl htc, chainStep] at hg
      rcases mem_foldl_push_cases _ _ _ _ _ hg with h | ⟨v, -, hT, rfl⟩
      · exact ih _ g h
      · exact (sameOrbit_spec hT).1

/-! ## The automorphism group is generated by the chain -/

/-- **The complete set of automorphism generators of `adj`**, in array form. -/
def chainArrays (n : Nat) (adj : Fin n → Fin n → Bool) : Array (Array Nat) :=
  chainGens n (oracleOfFin n adj) (n + 1) #[]

theorem chainArrays_isAuto {n : Nat} {adj : Fin n → Fin n → Bool} {g : Array Nat}
    (hg : g ∈ chainArrays n adj) : IsAutoArr n (oracleOfFin n adj) g :=
  chainGens_isAuto n (oracleOfFin n adj) (n + 1) #[] g hg

theorem mem_autGroup_of_mem_permsOf {n : Nat} {adj : Fin n → Fin n → Bool}
    {gs : Array (Array Nat)} (hgs : ∀ g ∈ gs, IsAutoArr n (oracleOfFin n adj) g)
    {τ : Equiv.Perm (Fin n)} (hτ : τ ∈ permsOf n gs) : τ ∈ autGroup n adj := by
  obtain ⟨g, hgmem, hval⟩ := hτ
  have hg := hgs g hgmem
  intro i j
  have h := hg.adj i.1 i.2 j.1 j.2
  rw [oracleOfFin_apply adj (hg.perm.lt i.1 i.2) (hg.perm.lt j.1 j.2),
    oracleOfFin_apply adj i.2 j.2, Fin.eta, Fin.eta] at h
  rw [show τ i = ⟨g[i.1]!, hg.perm.lt i.1 i.2⟩ from Fin.ext (hval i),
    show τ j = ⟨g[j.1]!, hg.perm.lt j.1 j.2⟩ from Fin.ext (hval j)]
  exact h

/-- **The automorphism computation is complete.**  The automorphism group of `adj` is exactly the
group generated by the permutations the stabiliser chain computes — not merely a subgroup of it. -/
theorem autGroup_eq_closure (n : Nat) (adj : Fin n → Fin n → Bool) :
    autGroup n adj = Subgroup.closure (permsOf n (chainArrays n adj)) := by
  refine _root_.le_antisymm (fun σ hσ => ?_) (Subgroup.closure_le _ |>.2 fun τ hτ =>
    mem_autGroup_of_mem_permsOf (fun _ hg => chainArrays_isAuto hg) hτ)
  exact chain_complete n adj (n + 1) #[] _ _ Node.root
    (by have := numCells_le (n := n) (rootPart n (oracleOfFin n adj)); omega) σ hσ (by simp)

/-- **A complete set of generators of the automorphism group**, as elements of `autGroup n adj`. -/
def fullGens (n : Nat) (adj : Fin n → Fin n → Bool) : Array (autGroup n adj) :=
  (chainArrays n adj).attach.map fun g => autGenOf n adj g.1 (chainArrays_isAuto g.2)

theorem coe_fullGens (n : Nat) (adj : Fin n → Fin n → Bool) :
    ((fun x : autGroup n adj => (x : Equiv.Perm (Fin n))) '' {x | x ∈ fullGens n adj})
      = permsOf n (chainArrays n adj) := by
  ext σ
  constructor
  · rintro ⟨x, hx, rfl⟩
    obtain ⟨⟨g, hg⟩, -, rfl⟩ := Array.mem_map.1 hx
    exact ⟨g, hg, fun i => permOfArrays_val (chainArrays_isAuto hg).perm.isPerm
      (fun x hx => invArray_apply (chainArrays_isAuto hg).perm.size
        (chainArrays_isAuto hg).perm.isPerm x hx) i⟩
  · rintro ⟨g, hg, hval⟩
    refine ⟨autGenOf n adj g (chainArrays_isAuto hg), Array.mem_map.2 ⟨⟨g, hg⟩, ?_, rfl⟩, ?_⟩
    · exact Array.mem_attach _ _
    · refine Equiv.ext fun i => Fin.ext ?_
      rw [hval i]
      exact permOfArrays_val (chainArrays_isAuto hg).perm.isPerm
        (fun x hx => invArray_apply (chainArrays_isAuto hg).perm.size
          (chainArrays_isAuto hg).perm.isPerm x hx) i

/-- **Completeness, in terms of `autGroup` elements**: `fullGens` generates the automorphism
group of `adj`. -/
theorem closure_fullGens (n : Nat) (adj : Fin n → Fin n → Bool) :
    Subgroup.closure {x : autGroup n adj | x ∈ fullGens n adj} = ⊤ := by
  apply Subgroup.map_injective (autGroup n adj).subtype_injective
  rw [MonoidHom.map_closure, ← MonoidHom.range_eq_map, Subgroup.range_subtype]
  rw [show ((autGroup n adj).subtype '' {x : autGroup n adj | x ∈ fullGens n adj}) =
    ((fun x : autGroup n adj => (x : Equiv.Perm (Fin n))) '' {x | x ∈ fullGens n adj}) from rfl,
    coe_fullGens]
  exact (autGroup_eq_closure n adj).symm

end Canon
end IsoGraph
