import Mathlib.Algebra.Group.Subgroup.Basic
import Mathlib.GroupTheory.Perm.Basic
import IsoGraph.Canon.Spec
import IsoGraph.Canon.Leaves

/-!
# The automorphism group, computed alongside the canonical labelling

The individualisation–refinement search of `IsoGraph.Canon.Algorithm` already discovers
automorphisms: every time it reaches a leaf whose certificate ties the current best one, the two
labellings differ by an automorphism, and it records that permutation in `St.autos` and uses it to
prune the rest of the search.  Those generators are thrown away by `canonPerm`, which keeps only
the labelling.  This file keeps them.

## What is here

* `autGroup n adj` — the automorphism group of a graph on `Fin n`, as a `Subgroup
  (Equiv.Perm (Fin n))`.
* `autGens n adj` — the generators the search harvested, as *elements of that subgroup*.  There
  is no run-time check involved: `Leaves.dfsNode_good` already proves that everything the search
  puts in `St.autos` is an automorphism, so the membership proof comes for free.
* `canonPermAndGens n adj` — **the pair entry point**: the canonical labelling and the generators,
  from a single run of the search.  `canonPerm` and `autGens` are its two projections
  definitionally, so nothing is recomputed by using it.
* `vertexTransitiveCert` and `arcTransitiveCert` — vertex- and arc-transitivity, decided by a
  breadth-first orbit search in the group generated by `autGens`.

## Certificates, and what is and is not proved

The subgroup generated by the harvested generators is not *proved* to be the whole automorphism
group — in fact nothing here depends on that, and it is why the transitivity tests return a
`Cert P` ("a proof of `P`, or nothing") rather than a `Decidable P`.  A `Cert` is data, so it can
be produced by the compiled search and consumed by `native_decide`:

```
example : ∀ i j : Fin 5, ∃ σ ∈ autGroup 5 adj, σ i = j :=
  (vertexTransitiveCert 5 adj).out (by native_decide)
```

Everything the search *does* return is honest: the orbit search hands back a word in the
generators for each point it reaches, and that word is then checked to move the base point where
it claims to.  A bug in the search can therefore only cost a `Cert.no`, never a wrong proof.  In
practice the harvested generators do generate the full group, so `Cert.no` means "not transitive".
-/

set_option autoImplicit false

namespace IsoGraph.Canon

variable {n : Nat}

/-! ## The automorphism group of a graph on `Fin n` -/

/-- The automorphism group of the graph `adj` on `Fin n`, as a subgroup of all permutations. -/
def autGroup (n : Nat) (adj : Fin n → Fin n → Bool) : Subgroup (Equiv.Perm (Fin n)) where
  carrier := {σ | ∀ i j, adj (σ i) (σ j) = adj i j}
  mul_mem' {σ τ} hσ hτ i j := by
    show adj (σ (τ i)) (σ (τ j)) = adj i j
    rw [hσ (τ i) (τ j), hτ i j]
  one_mem' _ _ := rfl
  inv_mem' {σ} hσ i j := by
    show adj (σ.symm i) (σ.symm j) = adj i j
    rw [← hσ (σ.symm i) (σ.symm j), Equiv.apply_symm_apply, Equiv.apply_symm_apply]

theorem mem_autGroup {adj : Fin n → Fin n → Bool} {σ : Equiv.Perm (Fin n)} :
    σ ∈ autGroup n adj ↔ ∀ i j, adj (σ i) (σ j) = adj i j := Iff.rfl

theorem autGroup_adj {adj : Fin n → Fin n → Bool} (σ : autGroup n adj) (i j : Fin n) :
    adj ((σ : Equiv.Perm (Fin n)) i) ((σ : Equiv.Perm (Fin n)) j) = adj i j := σ.2 i j

/-! ## The generators the search harvests -/

/-- **Every automorphism the search records is genuine.**  This is `Leaves.dfsNode_good`, whose
`StGood` invariant carries exactly this, read off at the root call. -/
theorem canonical_autos_isAuto (m : Nat) (f : Nat → Nat → Bool) {g : Array Nat}
    (hg : g ∈ (canonical (Graph.ofOracle m f)).autos) : IsAutoArr m f g := by
  have hgood : StGood m f (canonSt m f) :=
    dfsNode_good m f (m + 1) #[] (rootInv m f) (rootPart m f) _ Node.root
      ⟨by simp, by simp, by simp⟩
  rw [canonical_eq] at hg
  rcases hb : (canonSt m f).best with _ | b
  · rw [hb] at hg; simp at hg
  · rw [hb] at hg; exact hgood.2.2 g hg

/-- An automorphism in array form, read as a permutation of `Fin n`, is an automorphism. -/
theorem permOfArrays_mem_autGroup {adj : Fin n → Fin n → Bool} {g : Array Nat}
    (h : IsAutoArr n (oracleOfFin n adj) g) :
    permOfArrays n g (invArray n g) ∈ autGroup n adj := by
  intro i j
  have hval : ∀ k : Fin n, (permOfArrays n g (invArray n g) k).1 = g[k.1]! := fun k =>
    permOfArrays_val h.perm.isPerm
      (fun x hx => invArray_apply h.perm.size h.perm.isPerm x hx) k
  have hi := h.perm.lt i.1 i.2
  have hj := h.perm.lt j.1 j.2
  rw [show permOfArrays n g (invArray n g) i = ⟨g[i.1]!, hi⟩ from Fin.ext (hval i),
    show permOfArrays n g (invArray n g) j = ⟨g[j.1]!, hj⟩ from Fin.ext (hval j)]
  have := h.adj i.1 i.2 j.1 j.2
  rwa [oracleOfFin_apply adj hi hj, oracleOfFin_apply adj i.2 j.2, Fin.eta, Fin.eta] at this

/-- Package an array-form automorphism as an element of `autGroup`.  Kept separate from `autGens`
so that elaboration never has to unfold the search to check the membership proof. -/
def autGenOf (n : Nat) (adj : Fin n → Fin n → Bool) (g : Array Nat)
    (hg : IsAutoArr n (oracleOfFin n adj) g) : autGroup n adj :=
  ⟨permOfArrays n g (invArray n g), permOfArrays_mem_autGroup hg⟩

/-- The automorphisms the search harvested, in raw array form. -/
def autoArrays (n : Nat) (adj : Fin n → Fin n → Bool) : Array (Array Nat) :=
  (canonical (Graph.ofOracle n (oracleOfFin n adj))).autos

/-- **The automorphism generators of `adj`**: what the canonical labelling search harvested along
the way, as elements of `autGroup n adj`.

These are generators of *a* subgroup of the automorphism group; for the usual reasons (this is
what nauty does) it is the whole group in practice, but nothing here relies on that. -/
def autGens (n : Nat) (adj : Fin n → Fin n → Bool) : Array (autGroup n adj) :=
  (autoArrays n adj).attach.map fun g =>
    autGenOf n adj g.1 (canonical_autos_isAuto n (oracleOfFin n adj) g.2)

/-! ## The pair entry point -/

/-- **One search, both halves**: the canonical labelling of `adj` *and* generators for its
automorphism group.

`canonPerm` and `autGens` are the two projections (`canonPermAndGens_fst`,
`canonPermAndGens_snd`), so a caller that wants both should ask for this pair rather than for the
two of them, which would run the search twice. -/
def canonPermAndGens (n : Nat) (adj : Fin n → Fin n → Bool) :
    Equiv.Perm (Fin n) × Array (autGroup n adj) :=
  let r := canonical (Graph.ofOracle n (oracleOfFin n adj))
  let lab := if isPermArray n r.lab then r.lab else Array.range n
  (permOfArrays n lab (invArray n lab),
    r.autos.attach.map fun g =>
      autGenOf n adj g.1 (canonical_autos_isAuto n (oracleOfFin n adj) g.2))

theorem canonPermAndGens_fst (n : Nat) (adj : Fin n → Fin n → Bool) :
    (canonPermAndGens n adj).1 = canonPerm n adj := rfl

theorem canonPermAndGens_snd (n : Nat) (adj : Fin n → Fin n → Bool) :
    (canonPermAndGens n adj).2 = autGens n adj := rfl

/-- The canonical form and the automorphism generators, from one search. -/
def canonMatrixAndGens (n : Nat) (adj : Fin n → Fin n → Bool) :
    AdjMatrix n × Array (autGroup n adj) :=
  let (σ, gens) := canonPermAndGens n adj
  (matrixOfPerm n adj σ, gens)

theorem canonMatrixAndGens_fst (n : Nat) (adj : Fin n → Fin n → Bool) :
    (canonMatrixAndGens n adj).1 = canonMatrix n adj := rfl

theorem canonMatrixAndGens_snd (n : Nat) (adj : Fin n → Fin n → Bool) :
    (canonMatrixAndGens n adj).2 = autGens n adj := rfl

/-! ## Words in the generators -/

/-- The product `gens[i₁] * gens[i₂] * ⋯` of the generators named by a word.  Out-of-range indices
contribute the identity, so this is total and no facts about the word are needed. -/
def wordAuto {adj : Fin n → Fin n → Bool} (gens : Array (autGroup n adj)) (w : List Nat) :
    autGroup n adj :=
  w.foldl (fun a i => a * gens.getD i 1) 1

/-- Apply generator number `k` to the point `v` (as a natural number `< n`). -/
def act {adj : Fin n → Fin n → Bool} (gens : Array (autGroup n adj)) (k v : Nat) : Nat :=
  if h : v < n then ((gens.getD k 1 : Equiv.Perm (Fin n)) ⟨v, h⟩).1 else v

/-- Breadth-first search of the orbit of `base` among `m` points, where generator number `k` sends
the point `p` to `succ k p`.  Returns, for every point reached, a word in the generators taking
`base` to it, and `none` for the points not reached.

Nothing is proved about this: the words it returns are *checked* by the caller, and a wrong word
only means a certificate fails to be found. -/
def bfsWords (m : Nat) (ngens : Nat) (succ : Nat → Nat → Nat) (base : Nat) :
    Array (Option (List Nat)) := Id.run do
  let mut w : Array (Option (List Nat)) := Array.replicate m none
  if base ≥ m then return w
  w := w.set! base (some [])
  let mut queue : Array Nat := #[base]
  for i in [0:m] do
    if h : i < queue.size then
      let v := queue[i]
      let wv := (w[v]!).getD []
      for k in [0:ngens] do
        let u := succ k v
        if u < m && (w[u]!).isNone then
          w := w.set! u (some (k :: wv))
          queue := queue.push u
  return w

/-! ## Certificates

`Option` lives in `Type`, so a search that either finds a proof or gives up cannot return
`Option P`.  `Cert P` is that type: a proof of `P`, or nothing.  The point of the wrapper is that
`Cert P` is *data*, so the search can be run by `native_decide` on `isYes` and the proof pulled
out afterwards with `Cert.out`. -/

/-- A proof of `P` produced by a search, or nothing.  See `Cert.out`. -/
inductive Cert (P : Prop) : Type
  /-- The search succeeded, with this proof. -/
  | yes (h : P) : Cert P
  /-- The search failed. -/
  | no : Cert P

/-- Did the search succeed?  The only thing `native_decide` has to evaluate. -/
def Cert.isYes {P : Prop} : Cert P → Bool
  | .yes _ => true
  | .no => false

/-- Extract the proof from a successful search. -/
theorem Cert.out {P : Prop} : ∀ c : Cert P, c.isYes = true → P
  | .yes h, _ => h

/-- Weaken a certificate along an implication.  The implication is a proof, so this stays
computable even when the implication is not. -/
def Cert.map {P Q : Prop} (f : P → Q) : Cert P → Cert Q
  | .yes h => .yes (f h)
  | .no => .no

@[simp] theorem Cert.isYes_map {P Q : Prop} (f : P → Q) (c : Cert P) :
    (c.map f).isYes = c.isYes := by cases c <;> rfl

/-! ## Transitivity -/

section Transitivity
variable {adj : Fin n → Fin n → Bool}

/-- From "every vertex is `base` moved by a known automorphism" to vertex-transitivity. -/
theorem vertexTransitive_of_words (base : Fin n) (m : Fin n → autGroup n adj)
    (h : ∀ j, (m j : Equiv.Perm (Fin n)) base = j) (i j : Fin n) :
    ∃ σ ∈ autGroup n adj, σ i = j := by
  refine ⟨(m j : Equiv.Perm (Fin n)) * ((m i : Equiv.Perm (Fin n)))⁻¹,
    mul_mem (m j).2 (inv_mem (m i).2), ?_⟩
  show (m j : Equiv.Perm (Fin n)) (((m i : Equiv.Perm (Fin n)))⁻¹ i) = j
  rw [show ((m i : Equiv.Perm (Fin n)))⁻¹ i = base from
    Equiv.Perm.inv_eq_iff_eq.2 (h i).symm, h j]

/-- From "every arc is the arc `(b₁, b₂)` moved by a known automorphism" to arc-transitivity.

Note that `(b₁, b₂)` is not required to be an arc: if it is not, then the hypothesis can only hold
when there are no arcs at all, and the conclusion is vacuous. -/
theorem arcTransitive_of_words (b₁ b₂ : Fin n) (m : Fin n → Fin n → autGroup n adj)
    (h : ∀ i j, adj i j = true →
      (m i j : Equiv.Perm (Fin n)) b₁ = i ∧ (m i j : Equiv.Perm (Fin n)) b₂ = j)
    (i j k l : Fin n) (hij : adj i j = true) (hkl : adj k l = true) :
    ∃ σ ∈ autGroup n adj, σ i = k ∧ σ j = l := by
  obtain ⟨h₁, h₂⟩ := h i j hij
  obtain ⟨h₃, h₄⟩ := h k l hkl
  refine ⟨(m k l : Equiv.Perm (Fin n)) * ((m i j : Equiv.Perm (Fin n)))⁻¹,
    mul_mem (m k l).2 (inv_mem (m i j).2), ?_, ?_⟩
  · show (m k l : Equiv.Perm (Fin n)) (((m i j : Equiv.Perm (Fin n)))⁻¹ i) = k
    rw [show ((m i j : Equiv.Perm (Fin n)))⁻¹ i = b₁ from
      Equiv.Perm.inv_eq_iff_eq.2 h₁.symm, h₃]
  · show (m k l : Equiv.Perm (Fin n)) (((m i j : Equiv.Perm (Fin n)))⁻¹ j) = l
    rw [show ((m i j : Equiv.Perm (Fin n)))⁻¹ j = b₂ from
      Equiv.Perm.inv_eq_iff_eq.2 h₂.symm, h₄]

end Transitivity

/-- **Vertex-transitivity of `adj`**, if the harvested generators are enough to see it.

The work is a breadth-first search of the orbit of vertex `0` under the generators; every word it
produces is then checked, so a bug in the search can only cost us a `Cert.no`. -/
def vertexTransitiveCert (n : Nat) (adj : Fin n → Fin n → Bool) :
    Cert (∀ i j : Fin n, ∃ σ ∈ autGroup n adj, σ i = j) :=
  if h : 0 < n then
    let base : Fin n := ⟨0, h⟩
    let gens := autGens n adj
    let ws := bfsWords n gens.size (act gens) 0
    let m : Fin n → autGroup n adj := fun j => wordAuto gens ((ws[j.1]!).getD [])
    if hc : ∀ j, (m j : Equiv.Perm (Fin n)) base = j then
      .yes (vertexTransitive_of_words base m hc)
    else .no
  else .yes fun i => absurd i.isLt (by omega)

/-- The first arc of `adj`, or `(0, 0)` if there is none.  Only a starting point for the orbit
search: nothing depends on it being an arc. -/
def firstArc (n : Nat) (adj : Fin n → Fin n → Bool) : Nat × Nat := Id.run do
  for i in [0:n] do
    for j in [0:n] do
      if oracleOfFin n adj i j then return (i, j)
  return (0, 0)

/-- **Arc-transitivity of `adj`**, if the harvested generators are enough to see it.

The same shape as `vertexTransitiveCert`, with the breadth-first search running on the `n²`
ordered pairs instead.  A graph with no arcs comes out arc-transitive for free. -/
def arcTransitiveCert (n : Nat) (adj : Fin n → Fin n → Bool) :
    Cert (∀ i j k l : Fin n, adj i j = true → adj k l = true →
      ∃ σ ∈ autGroup n adj, σ i = k ∧ σ j = l) :=
  if h : 0 < n then
    let a := firstArc n adj
    let b₁ : Fin n := ⟨a.1 % n, Nat.mod_lt _ h⟩
    let b₂ : Fin n := ⟨a.2 % n, Nat.mod_lt _ h⟩
    let gens := autGens n adj
    let ws := bfsWords (n * n) gens.size
      (fun k p => act gens k (p / n) * n + act gens k (p % n)) (b₁.1 * n + b₂.1)
    let m : Fin n → Fin n → autGroup n adj :=
      fun i j => wordAuto gens ((ws[i.1 * n + j.1]!).getD [])
    if hc : ∀ i j, adj i j = true →
        (m i j : Equiv.Perm (Fin n)) b₁ = i ∧ (m i j : Equiv.Perm (Fin n)) b₂ = j then
      .yes (arcTransitive_of_words b₁ b₂ m hc)
    else .no
  else .yes fun i => absurd i.isLt (by omega)

/-! ## Diagnostics

Unverified, and not used by anything above: the order of the group generated by the harvested
permutations, computed by simply enumerating it.  That is exponentially worse than the
Schreier–Sims algorithm one would normally use, but it is obviously correct, and the point here is
to have a number to look at (`#eval`), not to have it fast. -/

/-- The order of the group generated by `gens` (permutations of `{0, …, n-1}` in array form), or
`none` if it exceeds `limit`.  Plain breadth-first enumeration of the group elements. -/
def groupOrder? (n : Nat) (gens : Array (Array Nat)) (limit : Nat) : Option Nat := Id.run do
  let e : Array Nat := Array.range n
  let mut seen : Std.HashSet (List Nat) := (∅ : Std.HashSet (List Nat)).insert e.toList
  let mut queue : Array (Array Nat) := #[e]
  let mut i := 0
  for _ in [0:limit] do
    if h : i < queue.size then
      let g := queue[i]
      i := i + 1
      for k in [0:gens.size] do
        let ga := gens[k]!
        let c : Array Nat := (Array.range n).map fun v => ga[g[v]!]!
        if !seen.contains c.toList then
          if seen.size ≥ limit then return none
          seen := seen.insert c.toList
          queue := queue.push c
  if i < queue.size then return none
  return some seen.size

/-- The order of the automorphism group of `adj`, as generated by the harvested generators, or
`none` if it exceeds `limit`.  Unverified; a diagnostic. -/
def autGroupOrder? (n : Nat) (adj : Fin n → Fin n → Bool) (limit : Nat := 100000) : Option Nat :=
  groupOrder? n (autoArrays n adj) limit

end IsoGraph.Canon
