import IsoGraph.Canon.Chain
import Mathlib.Algebra.Group.Subgroup.Pointwise
import Mathlib.SetTheory.Cardinal.Finite

/-!
# The order of the automorphism group

`Canon/Group.lean` ends with `groupOrder?`, a breadth-first sweep over the group generated by some
permutations.  It is honest about being a diagnostic: nothing checks that the sweep terminated for
the right reason, or that the generators it was handed generate anything in particular.  This file
turns it into a theorem.

Two things have to be true of a list `E` of permutations, given in the array form the canonical
labelling search uses throughout, for it to *be* the automorphism group of `adj`:

* every entry is an automorphism — then `E` is contained in the group;
* `E` contains the identity and is closed under left multiplication by each generator of
  `chainArrays n adj` and by each of their inverses — then, since those generators generate the
  whole group (`autGroup_eq_closure`), the group is contained in `E`.

That is `AutElems`, and `Subgroup.closure_induction_left` is exactly the induction principle it is
shaped for: one case for the identity, one for `g ↦ t * g`, one for `g ↦ t⁻¹ * g`.  Add that `E`
has no repeats and its length *is* the order of the group.

## What is here

* `permComp n a b` — composition of two permutations in array form.
* `AutElems n adj E` — the four conditions above, and `card_autGroup`, which turns them into
  `Nat.card (autGroup n adj) = E.size`.
* `autElemsB` — the same conditions as a `Bool`, with `autElems_of_autElemsB` to cash it in.
* `enumPerms` — the unverified breadth-first search that produces a candidate `E`.  It may return
  nonsense; `autElemsB` is what stands behind the theorem.
* `autOrderCheck n adj limit k` — search, then check, then compare against `k`.  `card_autGroup_eq`
  is the payoff: a `Bool` that decides the order of an automorphism group.
-/

set_option autoImplicit false
namespace IsoGraph
namespace Canon

open Std

/-! ## Composing permutations in array form -/

/-- The composite `a ∘ b` of two permutations of `Fin n` written as arrays. -/
def permComp (n : Nat) (a b : Array Nat) : Array Nat :=
  Array.ofFn fun i : Fin n => a[b[i.1]!]!

theorem permComp_get {n : Nat} (a b : Array Nat) {i : Nat} (hi : i < n) :
    (permComp n a b)[i]! = a[b[i]!]! := by
  rw [permComp, getElem!_pos _ i (by simpa using hi)]
  simp

/-! ## Permutations named by arrays

`permsOf n E` is the set of permutations some entry of `E` names.  These three lemmas say that it
contains the identity and is closed under the two operations `closure_induction_left` uses, as
soon as the corresponding arrays are in `E`. -/

theorem one_mem_permsOf {n : Nat} {E : Array (Array Nat)} (h : Array.range n ∈ E) :
    (1 : Equiv.Perm (Fin n)) ∈ permsOf n E :=
  ⟨Array.range n, h, fun i => by rw [getElem!_pos _ i.1 (by simp)]; simp⟩

theorem mul_mem_permsOf {n : Nat} {E : Array (Array Nat)} {σ τ : Equiv.Perm (Fin n)}
    {a b : Array Nat} (ha : ∀ i : Fin n, (σ i).1 = a[i.1]!)
    (hb : ∀ i : Fin n, (τ i).1 = b[i.1]!) (hmem : permComp n a b ∈ E) :
    σ * τ ∈ permsOf n E :=
  ⟨permComp n a b, hmem, fun i => by
    rw [permComp_get a b i.2, Equiv.Perm.mul_apply, ha (τ i), hb i]⟩

/-- If `a` names `σ` then `invArray n a` names `σ⁻¹`. -/
theorem inv_named {n : Nat} {a : Array Nat} (hperm : PermArr n a) {σ : Equiv.Perm (Fin n)}
    (ha : ∀ i : Fin n, (σ i).1 = a[i.1]!) (i : Fin n) : (σ⁻¹ i).1 = (invArray n a)[i.1]! := by
  have h : a[(σ⁻¹ i).1]! = i.1 := by rw [← ha (σ⁻¹ i)]; simp
  have h2 : (invArray n a)[a[(σ⁻¹ i).1]!]! = (σ⁻¹ i).1 :=
    invArray_apply hperm.size hperm.isPerm _ (σ⁻¹ i).2
  rw [h] at h2
  exact h2.symm

/-! ## Listing the automorphism group -/

/-- What has to hold of `E` for it to list every automorphism of `adj` exactly once. -/
structure AutElems (n : Nat) (adj : Fin n → Fin n → Bool) (E : Array (Array Nat)) : Prop where
  /-- Everything listed is an automorphism. -/
  auto : ∀ g ∈ E, IsAutoArr n (oracleOfFin n adj) g
  /-- The identity is listed. -/
  one : Array.range n ∈ E
  /-- Multiplying on the left by a generator of the stabiliser chain stays inside the list. -/
  closed : ∀ t ∈ chainArrays n adj, ∀ g ∈ E, permComp n t g ∈ E
  /-- And so does multiplying by the inverse of one. -/
  closedInv : ∀ t ∈ chainArrays n adj, ∀ g ∈ E, permComp n (invArray n t) g ∈ E
  /-- Nothing is listed twice. -/
  nodup : E.toList.Nodup

/-- The half of `AutElems` that needs the stabiliser chain to be complete: every automorphism is
named by an entry of `E`.  The induction is over `autGroup_eq_closure`, peeling generators off the
left. -/
theorem mem_permsOf_of_mem_autGroup {n : Nat} {adj : Fin n → Fin n → Bool}
    {E : Array (Array Nat)} (h : AutElems n adj E) {σ : Equiv.Perm (Fin n)}
    (hσ : σ ∈ autGroup n adj) : σ ∈ permsOf n E := by
  rw [autGroup_eq_closure] at hσ
  induction hσ using Subgroup.closure_induction_left with
  | one => exact one_mem_permsOf h.one
  | mul_left x hx y _ ih =>
    obtain ⟨t, ht, hxt⟩ := hx
    obtain ⟨g, hg, hyg⟩ := ih
    exact mul_mem_permsOf hxt hyg (h.closed t ht g hg)
  | inv_mul_cancel x hx y _ ih =>
    obtain ⟨t, ht, hxt⟩ := hx
    obtain ⟨g, hg, hyg⟩ := ih
    exact mul_mem_permsOf (fun i => inv_named (chainArrays_isAuto ht).perm hxt i) hyg
      (h.closedInv t ht g hg)

/-- **`E` names the automorphism group exactly.** -/
theorem coe_autGroup {n : Nat} {adj : Fin n → Fin n → Bool} {E : Array (Array Nat)}
    (h : AutElems n adj E) : (autGroup n adj : Set (Equiv.Perm (Fin n))) = permsOf n E :=
  Set.ext fun _ => ⟨fun hσ => mem_permsOf_of_mem_autGroup h hσ,
    fun hσ => mem_autGroup_of_mem_permsOf h.auto hσ⟩

/-- **The order of the automorphism group is the length of the list**: reading an entry of `E` as a
permutation is a bijection onto `autGroup n adj`.  It is injective because `E` has no repeats and
an entry is recoverable from the permutation it names, and surjective by `coe_autGroup`. -/
theorem card_autGroup {n : Nat} {adj : Fin n → Fin n → Bool} {E : Array (Array Nat)}
    (h : AutElems n adj E) : Nat.card (autGroup n adj) = E.size := by
  have hauto : ∀ (k : Nat) (hk : k < E.size), IsAutoArr n (oracleOfFin n adj) (E[k]'hk) :=
    fun _ hk => h.auto _ (Array.getElem_mem hk)
  set F : Fin E.size → autGroup n adj := fun k =>
    ⟨permOfArrays n (E[k.1]'k.2) (invArray n (E[k.1]'k.2)),
      mem_autGroup_permOfArrays (hauto k.1 k.2)⟩ with hF
  have hinj : Function.Injective F := by
    intro k l hkl
    have hval : permOfArrays n (E[k.1]'k.2) (invArray n (E[k.1]'k.2))
        = permOfArrays n (E[l.1]'l.2) (invArray n (E[l.1]'l.2)) := congrArg Subtype.val hkl
    have hv : ∀ i : Fin n, (E[k.1]'k.2)[i.1]! = (E[l.1]'l.2)[i.1]! := by
      intro i
      rw [← permOfArrays_val_of_isAuto (hauto k.1 k.2) i,
        ← permOfArrays_val_of_isAuto (hauto l.1 l.2) i, hval]
    have harr : (E[k.1]'k.2) = (E[l.1]'l.2) := by
      have hsk := (hauto k.1 k.2).perm.size
      have hsl := (hauto l.1 l.2).perm.size
      apply Array.ext
      · rw [hsk, hsl]
      · intro i hik hil
        have hin : i < n := hsk ▸ hik
        have hi := hv ⟨i, hin⟩
        rwa [getElem!_pos _ i hik, getElem!_pos _ i hil] at hi
    have hl : E.toList[k.1]'(by simp) = E.toList[l.1]'(by simp) := by simpa using harr
    exact Fin.ext (h.nodup.getElem_inj_iff.mp hl)
  have hsurj : Function.Surjective F := by
    rintro ⟨σ, hσ⟩
    obtain ⟨g, hg, hgσ⟩ := mem_permsOf_of_mem_autGroup h hσ
    obtain ⟨k, hk, hkg⟩ := Array.mem_iff_getElem.1 hg
    refine ⟨⟨k, hk⟩, Subtype.ext (Equiv.ext fun i => Fin.ext ?_)⟩
    rw [hF, permOfArrays_val_of_isAuto (hauto k hk) i, hgσ i, hkg]
  have hcard := Nat.card_congr (Equiv.ofBijective F ⟨hinj, hsurj⟩)
  simpa using hcard.symm

/-! ## Deciding it -/

/-- `AutElems` as a `Bool`. -/
def autElemsB (n : Nat) (adj : Fin n → Fin n → Bool) (E : Array (Array Nat)) : Bool :=
  decide (∀ g ∈ E.toList, isAutoArrB n (oracleOfFin n adj) g = true) &&
    decide (Array.range n ∈ E.toList) &&
    decide (∀ t ∈ (chainArrays n adj).toList, ∀ g ∈ E.toList,
      permComp n t g ∈ E.toList ∧ permComp n (invArray n t) g ∈ E.toList) &&
    decide E.toList.Nodup

theorem autElems_of_autElemsB {n : Nat} {adj : Fin n → Fin n → Bool} {E : Array (Array Nat)}
    (h : autElemsB n adj E = true) : AutElems n adj E := by
  simp only [autElemsB, Bool.and_eq_true, decide_eq_true_eq] at h
  obtain ⟨⟨⟨h1, h2⟩, h3⟩, h4⟩ := h
  refine ⟨fun g hg => isAutoArrB_iff.1 (h1 g (by simpa using hg)), by simpa using h2,
    fun t ht g hg => ?_, fun t ht g hg => ?_, h4⟩
  · simpa using (h3 t (by simpa using ht) g (by simpa using hg)).1
  · simpa using (h3 t (by simpa using ht) g (by simpa using hg)).2

/-- Breadth-first enumeration of the group generated by `gens`, in array form, exploring at most
`limit` elements.  Unverified — running out of fuel just returns a short list, and `autElemsB` is
what decides whether the answer is any good. -/
def enumPerms (n : Nat) (gens : Array (Array Nat)) (limit : Nat) : Array (Array Nat) := Id.run do
  let e : Array Nat := Array.range n
  let mut seen : HashSet (List Nat) := (∅ : HashSet (List Nat)).insert e.toList
  let mut out : Array (Array Nat) := #[e]
  let mut i := 0
  for _ in [0:limit] do
    if i < out.size then
      let g := out[i]!
      i := i + 1
      for t in gens do
        let c := permComp n t g
        if !seen.contains c.toList then
          seen := seen.insert c.toList
          out := out.push c
  return out

/-- Every automorphism of `adj`, enumerated from the stabiliser chain's generators. -/
def autElems (n : Nat) (adj : Fin n → Fin n → Bool) (limit : Nat) : Array (Array Nat) :=
  enumPerms n (chainArrays n adj) limit

/-- **Does `adj` have exactly `k` automorphisms?**  Enumerate them, check the enumeration, and
count.  The cost of the check is quadratic in `k`, so this is for small groups. -/
def autOrderCheck (n : Nat) (adj : Fin n → Fin n → Bool) (limit k : Nat) : Bool :=
  let E := autElems n adj limit
  autElemsB n adj E && (E.size == k)

/-- **The order of the automorphism group, decided.** -/
theorem card_autGroup_eq {n : Nat} {adj : Fin n → Fin n → Bool} {limit k : Nat}
    (h : autOrderCheck n adj limit k = true) : Nat.card (autGroup n adj) = k := by
  simp only [autOrderCheck, Bool.and_eq_true, beq_iff_eq] at h
  rw [card_autGroup (autElems_of_autElemsB h.1), h.2]

end Canon
end IsoGraph
