import IsoGraph.Canon.Chain
import Mathlib.Algebra.Group.Action.End
import Mathlib.Algebra.Group.Action.Prod
import Mathlib.Data.Fintype.Prod

/-!
# Vertex- and arc-transitivity, decided

`Canon/Chain.lean` computes a set of automorphisms that is *proved* to generate the whole
automorphism group (`autGroup_eq_closure`).  With that in hand transitivity is no longer a matter
of finding a witness and hoping: the orbit of a point under the generated group is computable, and
a point outside it is outside the orbit of the *whole* group.  So the tests here decide, and they
decide falsehood as well as truth.

## What is here

* `orbitFin L a` — the orbit of `a` under the group generated by a list `L` of permutations,
  computed by saturating `{a}` one round at a time and stopping when a round adds nothing.  Nothing
  about the group is assumed: `exists_smul_eq_of_mem_orbitFin` says everything in it is reached by
  the group, and `smul_mem_orbitFin_of_mem_closure` says the group cannot leave it (given that `L`
  is closed under inverses, which `autPerms` is).
* `autPerms n adj` — the complete generators of `Canon/Chain.lean` as permutations, together with
  their inverses; `closure_autPerms` identifies the group they generate as `autGroup n adj`.
* `vertexTransitiveB` and `arcTransitiveB` — the two tests, with `vertexTransitiveB_iff` and
  `arcTransitiveB_iff` saying exactly what a `true` *and* a `false` mean.  `arcTransitiveBFast` is
  what the second one runs.

The saturation is deliberately naive — a `Finset` union per generator per round — and for an
orbit of *vertices* that is the right call, because the expensive part is upstream: `chainArrays`
searches a subtree for every candidate point its own orbit test does not already reach.  An orbit
of *arcs* is a different size of problem, and `arcTransitiveBFast` computes that one by
breadth-first search over a table of `n * n` bits.
-/

set_option autoImplicit false
namespace IsoGraph
namespace Canon

/-! ## Orbits of a finite group action, computed -/

section Orbit

variable {G α : Type*} [Group G] [MulAction G α] [DecidableEq α] [Fintype α]

/-- One round of saturation: add `g • x` for every `g` in `L` and every `x` in `S`. -/
def orbitStep (L : List G) (S : Finset α) : Finset α :=
  L.foldl (fun acc g => acc ∪ S.image (fun x => g • x)) S

omit [Fintype α] in
theorem subset_foldl_union (S : Finset α) :
    ∀ (L : List G) (init : Finset α),
      init ⊆ L.foldl (fun acc g => acc ∪ S.image (fun x => g • x)) init := by
  intro L
  induction L with
  | nil => intro init; simp
  | cons g L ih => intro init x hx; exact ih _ (Finset.mem_union_left _ hx)

omit [Fintype α] in
theorem subset_orbitStep (L : List G) (S : Finset α) : S ⊆ orbitStep L S :=
  subset_foldl_union S L S

omit [Fintype α] in
theorem smul_mem_orbitStep {L : List G} {S : Finset α} {g : G} (hg : g ∈ L) {x : α} (hx : x ∈ S) :
    g • x ∈ orbitStep L S := by
  show g • x ∈ L.foldl (fun acc h => acc ∪ S.image (fun y => h • y)) S
  suffices h : ∀ (L : List G), g ∈ L → ∀ init : Finset α,
      g • x ∈ L.foldl (fun acc h => acc ∪ S.image (fun y => h • y)) init from h L hg S
  intro L
  induction L with
  | nil => intro hg; simp at hg
  | cons a L ih =>
    intro hg init
    rcases List.mem_cons.1 hg with rfl | hg'
    · exact subset_foldl_union S L _ (Finset.mem_union_right _ (Finset.mem_image_of_mem _ hx))
    · exact ih hg' _

omit [Fintype α] in
theorem orbitStep_subset {L : List G} {S T : Finset α} (hS : S ⊆ T)
    (hT : ∀ g ∈ L, ∀ x ∈ T, g • x ∈ T) : orbitStep L S ⊆ T := by
  show L.foldl (fun acc h => acc ∪ S.image (fun y => h • y)) S ⊆ T
  revert hT
  suffices h : ∀ (L : List G), (∀ g ∈ L, ∀ x ∈ T, g • x ∈ T) → ∀ init ⊆ T,
      L.foldl (fun acc h => acc ∪ S.image (fun y => h • y)) init ⊆ T by
    intro hT; exact h L hT S hS
  intro L
  induction L with
  | nil => intro _ init hinit; simpa using hinit
  | cons a L ih =>
    intro hT init hinit
    refine ih (fun g hg => hT g (List.mem_cons_of_mem _ hg)) _ ?_
    intro x hx
    rcases Finset.mem_union.1 hx with h | h
    · exact hinit h
    · obtain ⟨y, hy, rfl⟩ := Finset.mem_image.1 h
      exact hT a (List.mem_cons_self ..) y (hS hy)

/-- Saturate `S` under the permutations in `L`, giving up after `fuel` rounds. -/
def saturate (L : List G) : Nat → Finset α → Finset α
  | 0, S => S
  | fuel + 1, S => if orbitStep L S = S then S else saturate L fuel (orbitStep L S)

omit [Fintype α] in
theorem subset_saturate (L : List G) : ∀ (fuel : Nat) (S : Finset α), S ⊆ saturate L fuel S := by
  intro fuel
  induction fuel with
  | zero => intro S; simp [saturate]
  | succ fuel ih =>
    intro S
    rw [saturate]
    split
    · exact Finset.Subset.refl S
    · exact (subset_orbitStep L S).trans (ih _)

omit [Fintype α] in
theorem saturate_subset {L : List G} {T : Finset α} (hT : ∀ g ∈ L, ∀ x ∈ T, g • x ∈ T) :
    ∀ (fuel : Nat) (S : Finset α), S ⊆ T → saturate L fuel S ⊆ T := by
  intro fuel
  induction fuel with
  | zero => intro S hS; simpa [saturate] using hS
  | succ fuel ih =>
    intro S hS
    rw [saturate]
    split
    · exact hS
    · exact ih _ (orbitStep_subset hS hT)

theorem orbitStep_saturate (L : List G) :
    ∀ (fuel : Nat) (S : Finset α), Fintype.card α ≤ S.card + fuel →
      orbitStep L (saturate L fuel S) = saturate L fuel S := by
  intro fuel
  induction fuel with
  | zero =>
    intro S hS
    have huniv : S = Finset.univ :=
      Finset.eq_univ_of_card S (le_antisymm (Finset.card_le_univ S) (by simpa using hS))
    subst huniv
    exact Finset.Subset.antisymm (Finset.subset_univ _) (subset_orbitStep L _)
  | succ fuel ih =>
    intro S hS
    rw [saturate]
    split
    · next h => exact h
    · next h =>
      refine ih _ ?_
      have hlt : S.card < (orbitStep L S).card :=
        Finset.card_lt_card (Finset.ssubset_iff_subset_ne.2 ⟨subset_orbitStep L S, fun he => h he.symm⟩)
      omega

/-- **The orbit of `a`** under the group generated by `L`. -/
def orbitFin (L : List G) (a : α) : Finset α := saturate L (Fintype.card α) {a}

theorem self_mem_orbitFin (L : List G) (a : α) : a ∈ orbitFin L a :=
  subset_saturate L _ _ (Finset.mem_singleton_self a)

theorem smul_mem_orbitFin {L : List G} {a : α} {g : G} (hg : g ∈ L) {x : α}
    (hx : x ∈ orbitFin L a) : g • x ∈ orbitFin L a := by
  have hfix : orbitStep L (orbitFin L a) = orbitFin L a :=
    orbitStep_saturate L _ _ (by simp)
  rw [← hfix]
  exact smul_mem_orbitStep hg hx

theorem smul_mem_orbitFin_of_mem_closure {L : List G} {a : α} (hL : ∀ g ∈ L, g⁻¹ ∈ L)
    {σ : G} (hσ : σ ∈ Subgroup.closure {g : G | g ∈ L}) {x : α} (hx : x ∈ orbitFin L a) :
    σ • x ∈ orbitFin L a := by
  have key : ∀ τ ∈ Subgroup.closure {g : G | g ∈ L},
      (∀ y ∈ orbitFin L a, τ • y ∈ orbitFin L a) ∧
        (∀ y ∈ orbitFin L a, τ⁻¹ • y ∈ orbitFin L a) := by
    intro τ hτ
    induction hτ using Subgroup.closure_induction with
    | mem g hg =>
      exact ⟨fun y hy => smul_mem_orbitFin hg hy, fun y hy => smul_mem_orbitFin (hL g hg) hy⟩
    | one => exact ⟨fun y hy => by simpa using hy, fun y hy => by simpa using hy⟩
    | mul x y _ _ ihx ihy =>
      exact ⟨fun z hz => by rw [mul_smul]; exact ihx.1 _ (ihy.1 _ hz),
        fun z hz => by rw [mul_inv_rev, mul_smul]; exact ihy.2 _ (ihx.2 _ hz)⟩
    | inv x _ ihx => exact ⟨fun z hz => ihx.2 _ hz, fun z hz => by rw [inv_inv]; exact ihx.1 _ hz⟩
  exact (key σ hσ).1 x hx

theorem exists_smul_eq_of_mem_orbitFin {L : List G} {a x : α} (hx : x ∈ orbitFin L a) :
    ∃ σ ∈ Subgroup.closure {g : G | g ∈ L}, σ • a = x := by
  classical
  set T : Finset α :=
    Finset.univ.filter fun b => ∃ σ ∈ Subgroup.closure {g : G | g ∈ L}, σ • a = b with hTdef
  have hT : ∀ g ∈ L, ∀ y ∈ T, g • y ∈ T := by
    intro g hg y hy
    obtain ⟨σ, hσ, rfl⟩ := (Finset.mem_filter.1 hy).2
    exact Finset.mem_filter.2 ⟨Finset.mem_univ _,
      ⟨g * σ, mul_mem (Subgroup.subset_closure hg) hσ, by rw [mul_smul]⟩⟩
  have hsub : orbitFin L a ⊆ T :=
    saturate_subset hT _ _ (Finset.singleton_subset_iff.2
      (Finset.mem_filter.2 ⟨Finset.mem_univ _, ⟨1, one_mem _, one_smul _ _⟩⟩))
  exact (Finset.mem_filter.1 (hsub hx)).2

end Orbit

/-! ## Transitivity, decided -/

variable {n : Nat}

/-- The complete generating set of `Canon/Chain.lean`, as permutations and closed under
inverses. -/
def autPerms (n : Nat) (adj : Fin n → Fin n → Bool) : List (Equiv.Perm (Fin n)) :=
  (fullGens n adj).toList.flatMap fun x : autGroup n adj =>
    [(x : Equiv.Perm (Fin n)), ((x : Equiv.Perm (Fin n)))⁻¹]

theorem mem_autPerms_iff {n : Nat} {adj : Fin n → Fin n → Bool} {g : Equiv.Perm (Fin n)} :
    g ∈ autPerms n adj ↔ ∃ x : autGroup n adj, x ∈ fullGens n adj ∧
      (g = (x : Equiv.Perm (Fin n)) ∨ g = ((x : Equiv.Perm (Fin n)))⁻¹) := by
  rw [autPerms, List.mem_flatMap]
  constructor
  · rintro ⟨x, hx, hg⟩
    refine ⟨x, Array.mem_toList_iff.1 hx, ?_⟩
    rcases List.mem_cons.1 hg with h | h
    · exact Or.inl h
    · rcases List.mem_cons.1 h with h' | h'
      · exact Or.inr h'
      · simp at h'
  · rintro ⟨x, hx, hg⟩
    refine ⟨x, Array.mem_toList_iff.2 hx, ?_⟩
    rcases hg with rfl | rfl
    · exact List.mem_cons_self ..
    · exact List.mem_cons_of_mem _ (List.mem_cons_self ..)

theorem inv_mem_autPerms {n : Nat} {adj : Fin n → Fin n → Bool} :
    ∀ g ∈ autPerms n adj, g⁻¹ ∈ autPerms n adj := by
  intro g hg
  obtain ⟨x, hx, hgx⟩ := mem_autPerms_iff.1 hg
  refine mem_autPerms_iff.2 ⟨x, hx, ?_⟩
  rcases hgx with rfl | rfl
  · exact Or.inr rfl
  · exact Or.inl (inv_inv _)

theorem mem_autGroup_of_mem_autPerms {n : Nat} {adj : Fin n → Fin n → Bool} :
    ∀ g ∈ autPerms n adj, g ∈ autGroup n adj := by
  intro g hg
  obtain ⟨x, -, hgx⟩ := mem_autPerms_iff.1 hg
  rcases hgx with rfl | rfl
  · exact x.2
  · exact inv_mem x.2

theorem closure_autPerms (n : Nat) (adj : Fin n → Fin n → Bool) :
    Subgroup.closure {g : Equiv.Perm (Fin n) | g ∈ autPerms n adj} = autGroup n adj := by
  refine _root_.le_antisymm ((Subgroup.closure_le _).2 mem_autGroup_of_mem_autPerms) ?_
  rw [autGroup_eq_closure]
  refine Subgroup.closure_mono ?_
  rw [← coe_fullGens]
  rintro σ ⟨x, hx, rfl⟩
  exact mem_autPerms_iff.2 ⟨x, hx, Or.inl rfl⟩

/-- **Vertex-transitivity of `adj`**: is the orbit of vertex `0` everything? -/
def vertexTransitiveB (n : Nat) (adj : Fin n → Fin n → Bool) : Bool :=
  if h : 0 < n then
    decide (orbitFin (autPerms n adj) (⟨0, h⟩ : Fin n) = Finset.univ)
  else true

theorem vertexTransitiveB_iff (n : Nat) (adj : Fin n → Fin n → Bool) :
    vertexTransitiveB n adj = true ↔ ∀ i j : Fin n, ∃ σ ∈ autGroup n adj, σ i = j := by
  unfold vertexTransitiveB
  split
  · next h =>
    rw [decide_eq_true_iff]
    constructor
    · intro huniv i j
      obtain ⟨σ, hσ, hσa⟩ :=
        exists_smul_eq_of_mem_orbitFin (L := autPerms n adj) (a := (⟨0, h⟩ : Fin n))
          (by rw [huniv]; exact Finset.mem_univ i)
      obtain ⟨τ, hτ, hτa⟩ :=
        exists_smul_eq_of_mem_orbitFin (L := autPerms n adj) (a := (⟨0, h⟩ : Fin n))
          (by rw [huniv]; exact Finset.mem_univ j)
      rw [closure_autPerms] at hσ hτ
      refine ⟨τ * σ⁻¹, mul_mem hτ (inv_mem hσ), ?_⟩
      rw [Equiv.Perm.smul_def] at hσa hτa
      rw [Equiv.Perm.mul_apply, ← hσa, Equiv.Perm.inv_def, Equiv.symm_apply_apply, hτa]
    · intro htr
      refine Finset.eq_univ_of_forall fun j => ?_
      obtain ⟨σ, hσ, hσj⟩ := htr ⟨0, h⟩ j
      rw [← closure_autPerms] at hσ
      have := smul_mem_orbitFin_of_mem_closure inv_mem_autPerms hσ
        (self_mem_orbitFin (autPerms n adj) (⟨0, h⟩ : Fin n))
      rwa [Equiv.Perm.smul_def, hσj] at this
  · next h =>
    simp only [true_iff]
    intro i
    exact absurd i.isLt (by omega)

/-- The arcs of `adj`: the ordered pairs of adjacent vertices. -/
def arcList (n : Nat) (adj : Fin n → Fin n → Bool) : List (Fin n × Fin n) :=
  (List.finRange n).flatMap fun i =>
    ((List.finRange n).filter fun j => adj i j).map fun j => (i, j)

theorem mem_arcList {n : Nat} {adj : Fin n → Fin n → Bool} {p : Fin n × Fin n} :
    p ∈ arcList n adj ↔ adj p.1 p.2 = true := by
  obtain ⟨i, j⟩ := p
  simp [arcList]

/-- **Arc-transitivity of `adj`**: is every arc in the orbit of the first one? -/
def arcTransitiveB (n : Nat) (adj : Fin n → Fin n → Bool) : Bool :=
  match arcList n adj with
  | [] => true
  | b :: _ => decide (∀ p ∈ arcList n adj, p ∈ orbitFin (autPerms n adj) b)

theorem arcTransitiveB_iff (n : Nat) (adj : Fin n → Fin n → Bool) :
    arcTransitiveB n adj = true ↔
      ∀ i j k l : Fin n, adj i j = true → adj k l = true →
        ∃ σ ∈ autGroup n adj, σ i = k ∧ σ j = l := by
  unfold arcTransitiveB
  rcases hl : arcList n adj with _ | ⟨b, rest⟩
  · simp only [true_iff]
    intro i j k l hij _
    have : (i, j) ∈ arcList n adj := mem_arcList.2 hij
    rw [hl] at this
    simp at this
  · have hb : b ∈ arcList n adj := by rw [hl]; exact List.mem_cons_self ..
    rw [decide_eq_true_iff]
    constructor
    · intro hall i j k l hij hkl
      obtain ⟨σ, hσ, hσb⟩ :=
        exists_smul_eq_of_mem_orbitFin (hall (i, j) (by rw [← hl]; exact mem_arcList.2 hij))
      obtain ⟨τ, hτ, hτb⟩ :=
        exists_smul_eq_of_mem_orbitFin (hall (k, l) (by rw [← hl]; exact mem_arcList.2 hkl))
      rw [closure_autPerms] at hσ hτ
      rw [Prod.ext_iff] at hσb hτb
      simp only [Prod.smul_fst, Prod.smul_snd, Equiv.Perm.smul_def] at hσb hτb
      refine ⟨τ * σ⁻¹, mul_mem hτ (inv_mem hσ), ?_, ?_⟩
      · rw [Equiv.Perm.mul_apply, ← hσb.1, Equiv.Perm.inv_def, Equiv.symm_apply_apply, hτb.1]
      · rw [Equiv.Perm.mul_apply, ← hσb.2, Equiv.Perm.inv_def, Equiv.symm_apply_apply, hτb.2]
    · intro htr p hp
      obtain ⟨σ, hσ, h1, h2⟩ :=
        htr b.1 b.2 p.1 p.2 (mem_arcList.1 hb) (mem_arcList.1 (by rw [hl]; exact hp))
      rw [← closure_autPerms] at hσ
      have hmem := smul_mem_orbitFin_of_mem_closure inv_mem_autPerms hσ
        (self_mem_orbitFin (autPerms n adj) b)
      have hsm : σ • b = p := by
        refine Prod.ext ?_ ?_ <;>
          simp only [Prod.smul_fst, Prod.smul_snd, Equiv.Perm.smul_def, h1, h2]
      rwa [hsm] at hmem

/-! ## The orbit of an arc, by breadth-first search

An orbit of *vertices* has at most `n` elements, and saturating a `Finset` of that size is
comfortable.  An orbit of *arcs* is a different size of problem — 2200 of them on the Higman–Sims
graph — and there the `Finset` is the wrong container: each round of `orbitStep` deduplicates and
unions lists that long, which is quadratic, and deciding arc-transitivity of the Higman–Sims graph
took seven minutes.  Below, the arcs get a table of `n * n` bits and the search expands only the
frontier; the same question now takes eight seconds, almost all of it the stabiliser chain.

The search itself is *not* proved correct, and does not have to be.  Its elements carry their
membership of `orbitFin` in their type, so whatever comes back is contained in the orbit; that it
is the *whole* orbit follows from a single check afterwards — that the list is closed under the
generators — because the orbit is the smallest closed set containing `b`.  That check reads the
table, so it is one array access per generator per arc.  Should it ever fail, the definition falls
back on the `Finset` saturation, which is why nothing here has to be trusted.
-/

/-- The index of the arc `p` in a table of `n * n` entries. -/
def arcIdx (n : Nat) (p : Fin n × Fin n) : Nat := p.1.val * n + p.2.val

theorem arcIdx_lt (p : Fin n × Fin n) : arcIdx n p < n * n := by
  have h1 : p.1.val + 1 ≤ n := p.1.isLt
  have h2 : p.2.val < n := p.2.isLt
  have h3 : (p.1.val + 1) * n ≤ n * n := Nat.mul_le_mul_right n h1
  have h4 : (p.1.val + 1) * n = p.1.val * n + n := Nat.succ_mul _ _
  simp only [arcIdx]
  omega

theorem arcIdx_injective : Function.Injective (arcIdx n) := by
  rintro ⟨a, b⟩ ⟨c, d⟩ h
  simp only [arcIdx] at h
  have hb : b.val < n := b.isLt
  have hd : d.val < n := d.isLt
  have hac : a.val = c.val := by
    rcases Nat.lt_trichotomy a.val c.val with hlt | heq | hgt
    · have h1 : (a.val + 1) * n ≤ c.val * n := Nat.mul_le_mul_right n hlt
      have h2 : (a.val + 1) * n = a.val * n + n := Nat.succ_mul _ _
      omega
    · exact heq
    · have h1 : (c.val + 1) * n ≤ a.val * n := Nat.mul_le_mul_right n hgt
      have h2 : (c.val + 1) * n = c.val * n + n := Nat.succ_mul _ _
      omega
  have hbd : b.val = d.val := by rw [hac] at h; omega
  exact Prod.ext (Fin.ext hac) (Fin.ext hbd)

/-- Is the arc `p` marked in the table `t`? -/
def arcTabGet (t : Vector Bool (n * n)) (p : Fin n × Fin n) : Bool := t[arcIdx n p]'(arcIdx_lt p)

/-- Mark the arc `p` in the table `t`. -/
def arcTabSet (t : Vector Bool (n * n)) (p : Fin n × Fin n) : Vector Bool (n * n) :=
  t.set (arcIdx n p) true (arcIdx_lt p)

theorem arcTabGet_replicate (p : Fin n × Fin n) :
    arcTabGet (Vector.replicate (n * n) false) p = false := by
  simp [arcTabGet]

theorem arcTabGet_arcTabSet (t : Vector Bool (n * n)) (p q : Fin n × Fin n) :
    arcTabGet (arcTabSet t q) p = (decide (p = q) || arcTabGet t p) := by
  simp only [arcTabGet, arcTabSet, Vector.getElem_set]
  by_cases h : arcIdx n q = arcIdx n p
  · have hpq : p = q := (arcIdx_injective h).symm
    simp [h, hpq]
  · have hpq : ¬ p = q := fun he => h (by rw [he])
    simp [h, hpq]

/-- Mark every arc of `C` in the table `t`. -/
def arcTableOn : List (Fin n × Fin n) → Vector Bool (n * n) → Vector Bool (n * n)
  | [], t => t
  | p :: C, t => arcTableOn C (arcTabSet t p)

theorem arcTabGet_arcTableOn (C : List (Fin n × Fin n)) (t : Vector Bool (n * n))
    (p : Fin n × Fin n) : arcTabGet (arcTableOn C t) p = (decide (p ∈ C) || arcTabGet t p) := by
  induction C generalizing t with
  | nil => simp [arcTableOn]
  | cons q C ih =>
    rw [arcTableOn, ih, arcTabGet_arcTabSet]
    simp [List.mem_cons, Bool.or_assoc, Bool.or_left_comm]

/-- **The table of the arcs in `C`.** -/
def arcTable (C : List (Fin n × Fin n)) : Vector Bool (n * n) :=
  arcTableOn C (Vector.replicate (n * n) false)

theorem arcTabGet_arcTable (C : List (Fin n × Fin n)) (p : Fin n × Fin n) :
    arcTabGet (arcTable C) p = true ↔ p ∈ C := by
  rw [arcTable, arcTabGet_arcTableOn, arcTabGet_replicate]
  simp

section Bfs

variable (L : List (Equiv.Perm (Fin n))) (b : Fin n × Fin n)

/-- Push `g • p` onto the frontier unless the table has it already.  The subtype is what makes
the search need no correctness proof: an element can only be built out of an element already in
the orbit. -/
private def pushArc (p : {p : Fin n × Fin n // p ∈ orbitFin L b})
    (st : Vector Bool (n * n) × List {p : Fin n × Fin n // p ∈ orbitFin L b})
    (g : {g : Equiv.Perm (Fin n) // g ∈ L}) :
    Vector Bool (n * n) × List {p : Fin n × Fin n // p ∈ orbitFin L b} :=
  let q : {p : Fin n × Fin n // p ∈ orbitFin L b} := ⟨g.1 • p.1, smul_mem_orbitFin g.2 p.2⟩
  if arcTabGet st.1 q.1 then st else (arcTabSet st.1 q.1, q :: st.2)

/-- One round: the images of the frontier that the table has not seen. -/
private def bfsRound (fr : List {p : Fin n × Fin n // p ∈ orbitFin L b})
    (t : Vector Bool (n * n)) :
    Vector Bool (n * n) × List {p : Fin n × Fin n // p ∈ orbitFin L b} :=
  fr.foldl (fun st p => L.attach.foldl (pushArc L b p) st) (t, [])

/-- Round after round until the frontier is empty. -/
private def bfsLoop : Nat → Vector Bool (n * n) →
    List {p : Fin n × Fin n // p ∈ orbitFin L b} →
    List {p : Fin n × Fin n // p ∈ orbitFin L b} →
    List {p : Fin n × Fin n // p ∈ orbitFin L b}
  | 0, _, _, acc => acc
  | _ + 1, _, [], acc => acc
  | fuel + 1, t, fr, acc =>
    let r := bfsRound L b fr t
    bfsLoop fuel r.1 r.2 (r.2 ++ acc)

/-- **The orbit of the arc `b`**, by breadth-first search over a table of the arcs seen. -/
def arcOrbitList : List (Fin n × Fin n) :=
  (bfsLoop L b (n * n + 1) (arcTabSet (Vector.replicate (n * n) false) b)
    [⟨b, self_mem_orbitFin L b⟩] [⟨b, self_mem_orbitFin L b⟩]).map Subtype.val

theorem mem_orbitFin_of_mem_arcOrbitList {p : Fin n × Fin n} (hp : p ∈ arcOrbitList L b) :
    p ∈ orbitFin L b := by
  obtain ⟨q, -, rfl⟩ := List.mem_map.1 hp
  exact q.2

private theorem mem_bfsLoop_of_mem (fuel : Nat) :
    ∀ (t : Vector Bool (n * n)) (fr acc : List {p : Fin n × Fin n // p ∈ orbitFin L b}) x,
      x ∈ acc → x ∈ bfsLoop L b fuel t fr acc := by
  induction fuel with
  | zero => intro t fr acc x hx; exact hx
  | succ fuel ih =>
    intro t fr acc x hx
    rcases fr with _ | ⟨p, fr⟩
    · exact hx
    · exact ih _ _ _ x (List.mem_append_right _ hx)

theorem mem_arcOrbitList_self : b ∈ arcOrbitList L b :=
  List.mem_map.2 ⟨⟨b, self_mem_orbitFin L b⟩,
    mem_bfsLoop_of_mem L b _ _ _ _ _ (List.mem_singleton_self _), rfl⟩

end Bfs

/-- Is `C` closed under `L`?  Read off the table, so a lookup is one array access. -/
def arcOrbitClosed (L : List (Equiv.Perm (Fin n))) (C : List (Fin n × Fin n))
    (t : Vector Bool (n * n)) : Bool :=
  C.all fun p => L.all fun g => arcTabGet t (g • p)

/-- **A list of orbit elements closed under `L` and containing `b` is the whole orbit**, since
the orbit is the smallest such set. -/
theorem mem_orbitFin_iff_of_closed {L : List (Equiv.Perm (Fin n))} {b : Fin n × Fin n}
    {C : List (Fin n × Fin n)} (hb : b ∈ C) (hC : ∀ p ∈ C, p ∈ orbitFin L b)
    (hcl : arcOrbitClosed L C (arcTable C) = true) (p : Fin n × Fin n) :
    p ∈ orbitFin L b ↔ p ∈ C := by
  refine ⟨fun hp => ?_, fun hp => hC p hp⟩
  have hT : ∀ g ∈ L, ∀ x ∈ C.toFinset, g • x ∈ C.toFinset := by
    intro g hg x hx
    rw [List.mem_toFinset] at hx ⊢
    have h1 := (List.all_eq_true.1 hcl) x hx
    have h2 := (List.all_eq_true.1 h1) g hg
    rwa [arcTabGet_arcTable] at h2
  have hsub : orbitFin L b ⊆ C.toFinset :=
    saturate_subset hT _ _ (Finset.singleton_subset_iff.2 (List.mem_toFinset.2 hb))
  exact List.mem_toFinset.1 (hsub hp)

/-- `arcTransitiveB`, with the orbit of the first arc found by breadth-first search and the scan
reading a table.

The specification writes `orbitFin (autPerms n adj) b` *under* the binder `p`, where nothing
hoists it: the whole stabiliser chain of `Canon/Chain.lean` is rerun for every arc.  Naming it in
a `let` outside the scan is worth 32 times on the Heawood graph, 23 on the Petersen graph and 98
on `C₄₆` (`testing/CacheBench.lean`, case `api-at`); computing it by breadth-first search instead
of `Finset` saturation is worth another 50 on the Higman–Sims graph. -/
def arcTransitiveBFast (n : Nat) (adj : Fin n → Fin n → Bool) : Bool :=
  match arcList n adj with
  | [] => true
  | b :: rest =>
    let L := autPerms n adj
    let C := arcOrbitList L b
    let t := arcTable C
    if arcOrbitClosed L C t then rest.all fun p => arcTabGet t p
    else
      let orb := orbitFin L b
      rest.all fun p => decide (p ∈ orb)

@[csimp] theorem arcTransitiveB_eq_arcTransitiveBFast :
    @arcTransitiveB = @arcTransitiveBFast := by
  funext n adj
  unfold arcTransitiveB arcTransitiveBFast
  generalize arcList n adj = l
  cases l with
  | nil => rfl
  | cons b rest =>
    simp only
    set L := autPerms n adj with hL
    set C := arcOrbitList L b with hC
    by_cases hcl : arcOrbitClosed L C (arcTable C) = true
    · rw [ite_eq_left hcl]
      have hmem := mem_orbitFin_iff_of_closed (L := L) (b := b) (C := C)
        (mem_arcOrbitList_self L b) (fun p hp => mem_orbitFin_of_mem_arcOrbitList L b hp) hcl
      rw [Bool.eq_iff_iff, decide_eq_true_eq, List.all_eq_true]
      refine ⟨fun hall p hp => ?_, fun hall p hp => ?_⟩
      · rw [arcTabGet_arcTable, ← hmem]
        exact hall p (List.mem_cons_of_mem _ hp)
      · rcases List.mem_cons.1 hp with rfl | hp'
        · exact self_mem_orbitFin L p
        · have h := hall p hp'
          rw [arcTabGet_arcTable, ← hmem] at h
          exact h
    · rw [ite_eq_right hcl]
      rw [Bool.eq_iff_iff, decide_eq_true_eq, List.all_eq_true]
      simp [self_mem_orbitFin]

end Canon
end IsoGraph
