import IsoGraph.Values.Identities.Semiring

/-!
# Factorisation in the graph semiring

`Identities/Semiring.lean` makes the graphs a commutative semiring twice over — under the disjoint
union with the cartesian product, and under the disjoint union with the strong product.  This
module asks which of the ring-theoretic classes of `Mathlib` those semirings satisfy.  The answer
is the same for both, and is proved once: every argument below runs over an abstract
`CommSemiring IsoGraph` whose `+` is the disjoint union and whose `*` multiplies vertex counts,
and is then instantiated in each scope.  What makes that possible is that the order `V` is a
semiring homomorphism to `ℕ` for both products, and that the multiset of connected components is
additive.

* The **units** are exactly the one-vertex graph, since `V` is multiplicative and `V G = 1` forces
  `G = empty 1`: that is `isUnit_iff_V`, and it makes every graph on a number of vertices that is
  prime irreducible.
* Divisibility is **well-founded**: a factorisation with a non-unit cofactor strictly decreases
  `V`, so `WfDvdMonoid` holds and every graph other than `empty 0` and `empty 1` is a product of
  irreducibles.
* The semiring is **local** in the degenerate way: a sum of two graphs is one vertex only if one
  summand is, so the non-units are closed under addition and form the unique maximal ideal.
* It is **not Noetherian**.  That maximal ideal is not finitely generated: a complete graph on a
  prime number of vertices is connected, so in any expression of it as a combination of finitely
  many generators exactly one term survives, and that generator has as many vertices as the prime.
* It is **not Bézout**, and so not a principal ideal ring: `Ideal.span {complete 2, complete 3}`
  would have to be generated by a graph whose order divides both `2` and `3`, hence by a unit, and
  then `c □g K₂ ⊕g d □g K₃ = K₁` for some `c` and `d`, which no vertex count allows.
* Factorisation is **not unique**.  Write `x` for `K₂`; then
  `(1 + x) * (1 + x² + x⁴) = (1 + x + x²) * (1 + x³)` in any commutative semiring, `1 + x` is
  irreducible because it has three vertices, and it divides neither factor on the right: not the
  first because `3 ∤ 7`, and not the second because `1 + x³` has a one-vertex component and a
  cofactor `c` of it would have to be one of the two components of `1 + x³` while having three
  vertices.  So `irreducible_iff_prime` fails, and with it `UniqueFactorizationMonoid`.

## What is not here

The failure of unique factorisation above is a failure of uniqueness and not of cancellation: both
`□g` and `⊠g` cancel a nonempty factor (Imrich, Klavžar and Rall, *Cancellation properties of
products of graphs*, Discrete Applied Mathematics 155 (2007) 2362–2364), as does `·g` on both sides
(Dörfler and Imrich, 1972).  For the strong product that is formalised, in
`Identities/Cancellation.lean`, so `IsCancelMulZero` and `IsDomain` hold there; the other two are
not.  The tensor product does not cancel at all, and that failure *is* formalised, as
`not_isCancelMulZero_tensorProduct`.

What is classical and missing is unique factorisation of *connected* graphs.  A connected graph factors uniquely into
connected graphs that are prime for `□g` — Sabidussi 1960 and Vizing 1963 — and for `⊠g` —
Dörfler and Imrich 1970, McKenzie 1971.  Together with cancellation this identifies the graph
semiring with the polynomial semiring `ℕ₀[Y]` on the connected primes (Imrich, Klep and Smertnig,
arXiv:2407.02615, Remark 3.17); unique factorisation then fails for the same reason it fails in
`ℕ₀[x]`, where `1 + x` is irreducible and not prime, and the six components of the identity above
are the fewest possible (Boiko, Cuno, Imrich, Lehner and van de Woestijne, arXiv:1103.0709).
`Identities/Connected.lean` collects the connected graphs into a submonoid of each product, which
is where such a theorem would land.
-/

set_option autoImplicit false

namespace IsoGraph

/-- A graph has no components exactly when it has no vertices. -/
theorem numComponents_eq_zero_iff_eq_empty {a : IsoGraph} :
    a.numComponents = 0 ↔ a = empty 0 := by
  rw [numComponents_eq_zero_iff, V_eq_zero_iff]

/-! ## The arguments, over an abstract structure

None of the six scopes of `Identities/Semiring.lean` is open here, so `*` below is whichever
product the caller supplies, and the properties of that product enter as hypotheses: `hV` says it
multiplies vertex counts, `hone` and `hzero` identify its unit and its zero, and `hadd` says the
addition is the disjoint union.  All four are `rfl` in every scope.  The two global `0` and `1`
instances have to be switched off for the section, or they would shadow those of the structure
being quantified over and no `Mathlib` lemma about `1` would apply. -/

section Abstract

attribute [-instance] IsoGraph.instZero IsoGraph.instOne

section Generic

variable [MonoidWithZero IsoGraph]
  (hzero : (0 : IsoGraph) = empty 0)
  (hone : (1 : IsoGraph) = empty 1)
  (hV : ∀ G H : IsoGraph, (G * H).V = G.V * H.V)

include hV in
/-- A factor has at most as many vertices as the product, and divides it. -/
theorem V_dvd_of_dvd {a b : IsoGraph} (h : a ∣ b) : a.V ∣ b.V := by
  obtain ⟨c, rfl⟩ := h
  exact ⟨c.V, hV a c⟩

include hone hV in
/-- **The one-vertex graph is the only unit.** -/
theorem isUnit_iff_V (G : IsoGraph) : IsUnit G ↔ G.V = 1 := by
  refine ⟨fun h ↦ ?_, fun h ↦ ?_⟩
  · obtain ⟨u, rfl⟩ := h
    have hu := congrArg IsoGraph.V u.mul_inv
    rw [hV, hone, V_empty] at hu
    exact Nat.eq_one_of_dvd_one ⟨_, hu.symm⟩
  · have hG : G = 1 := by rw [hone]; exact V_eq_one_iff.1 h
    exact hG ▸ isUnit_one

include hone hV in
/-- **A graph on a prime number of vertices is irreducible**, there being nowhere for the vertices
of a factorisation to go. -/
theorem irreducible_of_prime_V {G : IsoGraph} (hp : Nat.Prime G.V) : Irreducible G := by
  refine ⟨fun h ↦ ?_, fun a b hab ↦ ?_⟩
  · rw [isUnit_iff_V hone hV] at h
    rw [h] at hp
    exact Nat.not_prime_one hp
  · have hVab := congrArg IsoGraph.V hab
    rw [hV] at hVab
    rw [isUnit_iff_V hone hV, isUnit_iff_V hone hV]
    rcases hp.eq_one_or_self_of_dvd a.V ⟨b.V, hVab⟩ with h | h
    · exact Or.inl h
    · refine Or.inr ?_
      rw [h] at hVab
      exact (Nat.eq_of_mul_eq_mul_left hp.pos (by rw [mul_one]; exact hVab)).symm

end Generic

section GenericComm

variable [CommMonoidWithZero IsoGraph]
  (hzero : (0 : IsoGraph) = empty 0)
  (hone : (1 : IsoGraph) = empty 1)
  (hV : ∀ G H : IsoGraph, (G * H).V = G.V * H.V)

include hzero hone hV in
/-- **Divisibility is well-founded**: dividing by a non-unit loses a vertex.  Only the graph on no
vertices needs an argument of its own, since everything divides it. -/
theorem wfDvdMonoid_of_V : WfDvdMonoid IsoGraph := by
  have hVz : ∀ a : IsoGraph, a.V = 0 ↔ a = 0 := by
    intro a; rw [hzero]; exact V_eq_zero_iff
  have key : ∀ n (a : IsoGraph), a.V ≤ n → a ≠ 0 → Acc DvdNotUnit a := by
    intro n
    induction n with
    | zero => exact fun a ha h0 ↦ absurd ((hVz a).1 (Nat.le_zero.1 ha)) h0
    | succ n ih =>
      refine fun a ha h0 ↦ Acc.intro _ (fun b hb ↦ ih b ?_ hb.1)
      obtain ⟨c, hc, rfl⟩ := hb.2
      rw [isUnit_iff_V hone hV] at hc
      have hb0 : b.V ≠ 0 := fun h ↦ hb.1 ((hVz b).1 h)
      have hc0 : c.V ≠ 0 := fun h ↦ h0 ((hVz _).1 (by rw [hV, h, mul_zero]))
      rw [hV] at ha
      have h2 : 2 ≤ c.V := by omega
      nlinarith [Nat.one_le_iff_ne_zero.2 hb0]
  refine ⟨⟨fun a ↦ ?_⟩⟩
  by_cases h : a = 0
  · exact h ▸ Acc.intro _ (fun b hb ↦ key b.V b le_rfl hb.1)
  · exact key a.V a le_rfl h

end GenericComm

section GenericSemiring

variable [CommSemiring IsoGraph]
  (hadd : ∀ G H : IsoGraph, G + H = G ⊕g H)
  (hzero : (0 : IsoGraph) = empty 0)
  (hone : (1 : IsoGraph) = empty 1)
  (hV : ∀ G H : IsoGraph, (G * H).V = G.V * H.V)

include hadd hone hV in
/-- **The graph semiring is local**: a disjoint union is one vertex only if a summand is. -/
theorem isLocalRing_of_V : IsLocalRing IsoGraph := by
  refine IsLocalRing.of_is_unit_or_is_unit_of_add_one (fun {a b} hab ↦ ?_)
  have h := congrArg IsoGraph.V hab
  rw [hadd, V_disjUnion, hone, V_empty] at h
  rw [isUnit_iff_V hone hV, isUnit_iff_V hone hV]
  omega

include hadd hone hV in
/-- **The graph semiring is not Bézout**: the ideal generated by `K₂` and `K₃` is not principal,
because a generator would have to have one vertex, and no combination of `K₂` and `K₃` is a single
vertex. -/
theorem not_isBezout_of_V : ¬ IsBezout IsoGraph := by
  intro hb
  have hfg : (Ideal.span {complete 2, complete 3} : Ideal IsoGraph).FG :=
    Submodule.fg_span (Set.toFinite _)
  obtain ⟨g, hg⟩ := (IsBezout.isPrincipal_of_FG _ hfg).principal
  have hmem : ∀ n : ℕ, complete n ∈ ({complete 2, complete 3} : Set IsoGraph) →
      g.V ∣ (complete n).V := by
    intro n hn
    obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.1 (hg ▸ Ideal.subset_span hn)
    exact V_dvd_of_dvd hV (Dvd.intro_left c hc)
  have h2 : g.V ∣ 2 := by simpa using hmem 2 (by simp)
  have h3 : g.V ∣ 3 := by simpa using hmem 3 (by simp)
  have htop : Ideal.span ({complete 2, complete 3} : Set IsoGraph) = ⊤ := by
    rw [hg]
    exact Ideal.span_singleton_eq_top.2
      ((isUnit_iff_V hone hV g).2 (Nat.eq_one_of_dvd_one (by simpa using Nat.dvd_gcd h2 h3)))
  have h1 : (1 : IsoGraph) ∈ Ideal.span ({complete 2, complete 3} : Set IsoGraph) := by
    rw [htop]; trivial
  obtain ⟨c, d, hcd⟩ := Ideal.mem_span_pair.1 h1
  have h := congrArg IsoGraph.V hcd
  rw [hadd, V_disjUnion, hV, hV, hone, V_empty] at h
  simp only [V_complete] at h
  omega

include hadd hone hV in
/-- **The graph semiring is not a principal ideal ring**, a principal ideal ring being Bézout. -/
theorem not_isPrincipalIdealRing_of_V : ¬ IsPrincipalIdealRing IsoGraph :=
  fun _ ↦ not_isBezout_of_V hadd hone hV inferInstance

include hadd hzero hV in
/-- The graphs that are not a single vertex: the non-units, which form an ideal because a disjoint
union has one vertex only if a summand does. -/
private def nonunitIdeal : Ideal IsoGraph where
  carrier := {G : IsoGraph | G.V ≠ 1}
  add_mem' := by
    intro a b ha hb
    simp only [Set.mem_setOf_eq, hadd, V_disjUnion] at *
    omega
  zero_mem' := by simp [hzero]
  smul_mem' := by
    intro c a ha h
    simp only [Set.mem_setOf_eq, smul_eq_mul, hV] at *
    exact ha (Nat.eq_one_of_dvd_one ⟨c.V, by rw [mul_comm]; exact h.symm⟩)

include hadd hzero hV in
/-- **The graph semiring is not Noetherian.**  Its maximal ideal is not finitely generated: pick a
prime larger than every generator's order, and expand the complete graph on that many vertices
over the generators.  The number of components is additive and the complete graph is connected, so
exactly one term of that expansion is nonzero and equals the complete graph itself; its generator
then has a number of vertices that divides the prime and is not one. -/
theorem not_isNoetherianRing_of_V : ¬ IsNoetherianRing IsoGraph := by
  classical
  intro hn
  obtain ⟨S, hS⟩ := (isNoetherianRing_iff_ideal_fg IsoGraph).1 hn (nonunitIdeal hadd hzero hV)
  obtain ⟨q, hqle, hq⟩ := Nat.exists_infinite_primes (S.sup IsoGraph.V + 2)
  have hncq : (complete q : IsoGraph).numComponents = 1 := by
    obtain ⟨m, rfl⟩ : ∃ m, q = m + 1 := ⟨q - 1, by have := hq.two_le; omega⟩
    exact numComponents_complete m
  have hmem : (complete q : IsoGraph) ∈ Ideal.span (S : Set IsoGraph) := by
    rw [hS]
    show (complete q : IsoGraph).V ≠ 1
    rw [V_complete]
    omega
  obtain ⟨f, -, hf⟩ := Submodule.mem_span_finset.1 hmem
  simp only [smul_eq_mul] at hf
  have hnc : ∀ a b : IsoGraph, (a + b).numComponents = a.numComponents + b.numComponents :=
    fun a b ↦ by rw [hadd, numComponents_disjUnion]
  let φ : IsoGraph →+ ℕ :=
    { toFun := IsoGraph.numComponents
      map_zero' := by rw [hzero]; simp
      map_add' := hnc }
  have hsum : ∑ a ∈ S, (f a * a).numComponents = 1 := by
    have hh := congrArg φ hf
    rwa [map_sum, show φ (complete q) = 1 from hncq] at hh
  obtain ⟨a₀, ha₀S, ha₀⟩ : ∃ a ∈ S, (f a * a).numComponents ≠ 0 :=
    Finset.exists_ne_zero_of_sum_ne_zero (by rw [hsum]; exact one_ne_zero)
  have hrest : ∀ a ∈ S.erase a₀, f a * a = 0 := by
    intro a ha
    have hle : (f a * a).numComponents ≤ ∑ x ∈ S.erase a₀, (f x * x).numComponents :=
      Finset.single_le_sum (f := fun x ↦ (f x * x).numComponents) (fun _ _ ↦ Nat.zero_le _) ha
    have hsplit : (f a₀ * a₀).numComponents + ∑ x ∈ S.erase a₀, (f x * x).numComponents
        = ∑ x ∈ S, (f x * x).numComponents :=
      Finset.add_sum_erase S (fun x ↦ (f x * x).numComponents) ha₀S
    rw [hsum] at hsplit
    rw [hzero]
    exact numComponents_eq_zero_iff_eq_empty.1 (by omega)
  have heq : (complete q : IsoGraph) = f a₀ * a₀ := by
    have hsplit : f a₀ * a₀ + ∑ x ∈ S.erase a₀, f x * x = ∑ x ∈ S, f x * x :=
      Finset.add_sum_erase S (fun x ↦ f x * x) ha₀S
    rw [← hf, ← hsplit, Finset.sum_congr rfl hrest, Finset.sum_const_zero, add_zero]
  have hdvd : a₀.V ∣ q := by
    have hh := V_dvd_of_dvd hV (Dvd.intro_left (f a₀) heq.symm)
    rwa [V_complete] at hh
  have hne1 : a₀.V ≠ 1 := by
    have hmem' : a₀ ∈ Ideal.span (S : Set IsoGraph) := Ideal.subset_span ha₀S
    rw [hS] at hmem'
    exact hmem'
  have hle : a₀.V ≤ S.sup IsoGraph.V := Finset.le_sup ha₀S
  have : a₀.V = q := (hq.eq_one_or_self_of_dvd _ hdvd).resolve_left hne1
  omega

include hadd hone hV in
/-- **An irreducible graph that is not prime.**  With `x` connected on two vertices, `1 + x` has
three vertices, and `(1 + x) * (1 + x² + x⁴) = (1 + x + x²) * (1 + x³)`.  It does not divide
`1 + x + x²`, which has seven vertices; and it does not divide `1 + x³` either, since a cofactor
would be a component of `1 + x³` and so have one or eight vertices rather than three. -/
theorem not_prime_one_add (x : IsoGraph) (hx : x.V = 2) (hx3 : (x * x * x).numComponents = 1) :
    ¬ Prime (1 + x) := by
  intro hp
  have hV1x : (1 + x : IsoGraph).V = 3 := by rw [hadd, V_disjUnion, hone, V_empty, hx]
  have hdvd : (1 + x) ∣ (1 + x + x * x) * (1 + x * x * x) :=
    ⟨1 + x * x + x * x * x * x, by ring⟩
  rcases hp.2.2 _ _ hdvd with h | h
  · have h7 := V_dvd_of_dvd hV h
    rw [hV1x, hadd, hadd, V_disjUnion, V_disjUnion, hone, V_empty, hV, hx] at h7
    omega
  · obtain ⟨c, hc⟩ := h
    have hc' : (1 : IsoGraph) + x * x * x = c + x * c := by rw [hc]; ring
    have hVc : c.V = 3 := by
      have hh := congrArg IsoGraph.V hc
      simp only [hadd, hV, V_disjUnion, hone, V_empty, hx] at hh
      omega
    have hVxc : (x * c).V = 6 := by rw [hV, hx, hVc]
    have hnc : ∀ a b : IsoGraph, (a + b).numComponents = a.numComponents + b.numComponents :=
      fun a b ↦ by rw [hadd, numComponents_disjUnion]
    have hnc1 : (1 : IsoGraph).numComponents = 1 := by rw [hone, numComponents_empty]
    have hncc : c.numComponents = 1 := by
      have hh := congrArg IsoGraph.numComponents hc'
      rw [hnc, hnc, hnc1, hx3] at hh
      have h1 : c.numComponents ≠ 0 := fun hzz ↦ by
        rw [numComponents_eq_zero_iff_eq_empty.1 hzz, V_empty] at hVc; omega
      have h2 : (x * c).numComponents ≠ 0 := fun hzz ↦ by
        rw [numComponents_eq_zero_iff_eq_empty.1 hzz, V_empty] at hVxc; omega
      omega
    have hcomps := congrArg IsoGraph.comps hc'
    rw [hadd, hadd, comps_disjUnion, comps_disjUnion, comps_eq_singleton hnc1,
      comps_eq_singleton hx3, comps_eq_singleton hncc] at hcomps
    have hmem : c ∈ ({(1 : IsoGraph)} + {x * x * x} : Multiset IsoGraph) := by
      rw [hcomps]; exact Multiset.mem_add.2 (Or.inl (Multiset.mem_singleton_self c))
    rw [Multiset.singleton_add, Multiset.mem_cons, Multiset.mem_singleton] at hmem
    rcases hmem with rfl | rfl
    · rw [hone, V_empty] at hVc; omega
    · rw [hV, hV, hx] at hVc; omega

include hadd hone hV in
/-- **Irreducible does not imply prime** in the graph semiring. -/
theorem exists_irreducible_not_prime (x : IsoGraph) (hx : x.V = 2)
    (hx3 : (x * x * x).numComponents = 1) : ∃ p : IsoGraph, Irreducible p ∧ ¬ Prime p := by
  refine ⟨1 + x, irreducible_of_prime_V hone hV ?_, not_prime_one_add hadd hone hV x hx hx3⟩
  rw [hadd, V_disjUnion, hone, V_empty, hx]
  exact Nat.prime_three

include hadd hone hV in
/-- **Graphs do not factor uniquely.** -/
theorem not_uniqueFactorizationMonoid_of_V (x : IsoGraph) (hx : x.V = 2)
    (hx3 : (x * x * x).numComponents = 1) : ¬ UniqueFactorizationMonoid IsoGraph := by
  intro _
  obtain ⟨p, hirr, hnp⟩ := exists_irreducible_not_prime hadd hone hV x hx hx3
  exact hnp (UniqueFactorizationMonoid.irreducible_iff_prime.1 hirr)

end GenericSemiring

end Abstract

/-! ## The scopes

Each scope of `Identities/Semiring.lean` that has a unit gets the results above, with the four
hypotheses discharged by `rfl`.  The three multiplicative scopes get what needs only a product;
the two semiring scopes get everything. -/

namespace CartesianProduct

/-- **The one-vertex graph is the only unit** of the cartesian product. -/
theorem isUnit_iff (G : IsoGraph) : IsUnit G ↔ G.V = 1 := isUnit_iff_V rfl V_cartesianProduct G

/-- A graph on a prime number of vertices is irreducible for the cartesian product. -/
theorem irreducible_of_prime_V {G : IsoGraph} (hp : Nat.Prime G.V) : Irreducible G :=
  IsoGraph.irreducible_of_prime_V rfl V_cartesianProduct hp

/-- **Divisibility for the cartesian product is well-founded.** -/
scoped instance instWfDvdMonoid : WfDvdMonoid IsoGraph :=
  wfDvdMonoid_of_V rfl rfl V_cartesianProduct

end CartesianProduct

namespace StrongProduct

/-- **The one-vertex graph is the only unit** of the strong product. -/
theorem isUnit_iff (G : IsoGraph) : IsUnit G ↔ G.V = 1 := isUnit_iff_V rfl V_strongProduct G

/-- A graph on a prime number of vertices is irreducible for the strong product. -/
theorem irreducible_of_prime_V {G : IsoGraph} (hp : Nat.Prime G.V) : Irreducible G :=
  IsoGraph.irreducible_of_prime_V rfl V_strongProduct hp

/-- **Divisibility for the strong product is well-founded.** -/
scoped instance instWfDvdMonoid : WfDvdMonoid IsoGraph :=
  wfDvdMonoid_of_V rfl rfl V_strongProduct

end StrongProduct

namespace LexProduct

/-- **The one-vertex graph is the only unit** of the lexicographic product. -/
theorem isUnit_iff (G : IsoGraph) : IsUnit G ↔ G.V = 1 := isUnit_iff_V rfl V_lexProduct G

/-- A graph on a prime number of vertices is irreducible for the lexicographic product. -/
theorem irreducible_of_prime_V {G : IsoGraph} (hp : Nat.Prime G.V) : Irreducible G :=
  IsoGraph.irreducible_of_prime_V rfl V_lexProduct hp

end LexProduct

namespace Semiring

/-- **The one-vertex graph is the only unit.** -/
theorem isUnit_iff (G : IsoGraph) : IsUnit G ↔ G.V = 1 := isUnit_iff_V rfl V_cartesianProduct G

/-- **Divisibility is well-founded**, so every graph on at least two vertices is a product of
irreducibles. -/
scoped instance instWfDvdMonoid : WfDvdMonoid IsoGraph :=
  wfDvdMonoid_of_V rfl rfl V_cartesianProduct

/-- **The graph semiring is local**, the one-vertex graph being its only unit. -/
scoped instance instIsLocalRing : IsLocalRing IsoGraph :=
  isLocalRing_of_V (fun _ _ ↦ rfl) rfl V_cartesianProduct

/-- **The graph semiring is not Bézout.** -/
theorem not_isBezout : ¬ IsBezout IsoGraph :=
  not_isBezout_of_V (fun _ _ ↦ rfl) rfl V_cartesianProduct

/-- **The graph semiring is not a principal ideal ring.** -/
theorem not_isPrincipalIdealRing : ¬ IsPrincipalIdealRing IsoGraph :=
  not_isPrincipalIdealRing_of_V (fun _ _ ↦ rfl) rfl V_cartesianProduct

/-- **The graph semiring is not Noetherian.** -/
theorem not_isNoetherianRing : ¬ IsNoetherianRing IsoGraph :=
  not_isNoetherianRing_of_V (fun _ _ ↦ rfl) rfl V_cartesianProduct

/-- The three-cube is connected. -/
private theorem cube_connected :
    ((complete 2 : IsoGraph) * complete 2 * complete 2).numComponents = 1 :=
  (numComponents_eq_one_iff _).2 (isConnected_cartesianProduct.2
    ⟨isConnected_cartesianProduct.2 ⟨isConnected_complete 1, isConnected_complete 1⟩,
      isConnected_complete 1⟩)

/-- **`K₁ ⊕g K₂` is irreducible but not prime.** -/
theorem exists_irreducible_not_prime : ∃ p : IsoGraph, Irreducible p ∧ ¬ Prime p :=
  IsoGraph.exists_irreducible_not_prime (fun _ _ ↦ rfl) rfl V_cartesianProduct (complete 2)
    (V_complete 2) cube_connected

/-- **Graphs do not factor uniquely** into irreducibles for the cartesian product. -/
theorem not_uniqueFactorizationMonoid : ¬ UniqueFactorizationMonoid IsoGraph :=
  not_uniqueFactorizationMonoid_of_V (fun _ _ ↦ rfl) rfl V_cartesianProduct (complete 2)
    (V_complete 2) cube_connected

end Semiring

namespace StrongSemiring

/-- **The one-vertex graph is the only unit.** -/
theorem isUnit_iff (G : IsoGraph) : IsUnit G ↔ G.V = 1 := isUnit_iff_V rfl V_strongProduct G

/-- **Divisibility is well-founded**, so every graph on at least two vertices is a product of
irreducibles. -/
scoped instance instWfDvdMonoid : WfDvdMonoid IsoGraph :=
  wfDvdMonoid_of_V rfl rfl V_strongProduct

/-- **The graph semiring is local**, the one-vertex graph being its only unit. -/
scoped instance instIsLocalRing : IsLocalRing IsoGraph :=
  isLocalRing_of_V (fun _ _ ↦ rfl) rfl V_strongProduct

/-- **The graph semiring is not Bézout.** -/
theorem not_isBezout : ¬ IsBezout IsoGraph :=
  not_isBezout_of_V (fun _ _ ↦ rfl) rfl V_strongProduct

/-- **The graph semiring is not a principal ideal ring.** -/
theorem not_isPrincipalIdealRing : ¬ IsPrincipalIdealRing IsoGraph :=
  not_isPrincipalIdealRing_of_V (fun _ _ ↦ rfl) rfl V_strongProduct

/-- **The graph semiring is not Noetherian.** -/
theorem not_isNoetherianRing : ¬ IsNoetherianRing IsoGraph :=
  not_isNoetherianRing_of_V (fun _ _ ↦ rfl) rfl V_strongProduct

/-- The strong cube of `K₂`, which is `K₈`, is connected. -/
private theorem cube_connected :
    ((complete 2 : IsoGraph) * complete 2 * complete 2).numComponents = 1 :=
  (numComponents_eq_one_iff _).2 (isConnected_strongProduct
    (isConnected_strongProduct (isConnected_complete 1) (isConnected_complete 1))
    (isConnected_complete 1))

/-- **`K₁ ⊕g K₂` is irreducible but not prime.** -/
theorem exists_irreducible_not_prime : ∃ p : IsoGraph, Irreducible p ∧ ¬ Prime p :=
  IsoGraph.exists_irreducible_not_prime (fun _ _ ↦ rfl) rfl V_strongProduct (complete 2)
    (V_complete 2) cube_connected

/-- **Graphs do not factor uniquely** into irreducibles for the strong product. -/
theorem not_uniqueFactorizationMonoid : ¬ UniqueFactorizationMonoid IsoGraph :=
  not_uniqueFactorizationMonoid_of_V (fun _ _ ↦ rfl) rfl V_strongProduct (complete 2)
    (V_complete 2) cube_connected

end StrongSemiring

end IsoGraph
